%
%
%
% matNMR v. 3.9.94 - A processing toolbox for NMR/EPR under MATLAB
%
% Copyright (c) 1997-2009  Jacco van Beek
% jabe@users.sourceforge.net
%
%
% This program is free software; you can redistribute it and/or
% modify it under the terms of the GNU General Public License
% as published by the Free Software Foundation; either version 2
% of the License, or (at your option) any later version.
% 
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with this program; if not, write to the Free Software
% Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
%
% --> gpl.txt
%
% Should yo be too lazy to do this, please remember:
%    - The code may be altered under the condition that all changes are clearly marked 
%      with your name and the date and that none of the names currently present in the 
%      code are removed.
%
% Furthermore:
%    -Please update the BugFixes.txt (i.e. the changelog file)!
%    -Please inform me of useful changes and annoying bugs!
%
% Jacco
%
%
% ====================================================================================
%
%
function CSApk_init;

% Initialize all the GUI controls for CSATENSORFIT
% 5-3-94 SMB (Bren@SLAC.stanford.edu)

%
% adapted for matNMR by Jacco van Beek
% 16-01-'07
%

global QmatNMR

%
%Here we create the main window...
%
        QmatNMR.ScreenSize = get(0, 'screensize');
	CSAFig = figure('numbertitle','off',...
	       'Name','CSATENSORFIT --- Fitting Routine for static CSA Tensors',...
	       'position',[((QmatNMR.ScreenSize(3)-900)/2) ((QmatNMR.ScreenSize(4)-700)/2) 900 700],...
	       'backingstore', 'on', ...
	       'paperorientation', 'landscape', ...
               'papertype', 'a4letter', ....
	       'paperunits', 'normalized', ...
	       'paperposition', [0.1 0.1 .8 .8], ...
	       'CloseRequestFCN', 'stopcsafit', ...
               'menubar', 'none', ...
	       'color', QmatNMR.ColorScheme.Figure1Back, ...
	       'Tag', 'CSAFit');
        if (QmatNMR.unittype == 1)
          set(CSAFig, 'resize', 'on');
        else
          set(CSAFig, 'resize', 'off');
        end
	set(gca, 'visible', 'off');

	%  Uimenubar Object Creation 

	QmatNMR.Q1 = uimenu('parent', CSAFig, 'label', '   Load parameters   ', 'Position', [1]);
		uimenu(QmatNMR.Q1, 'label', 'Load parameters', 'callback', 'csafit(''loadpars1'');');

	QmatNMR.Q2 = uimenu('parent', CSAFig, 'label', '   View Fit Results   ', 'Position', [2]);
		uimenu(QmatNMR.Q2, 'label', 'Define Results Variable', 'callback', 'csafit(''defvar1'');');
		uimenu(QmatNMR.Q2, 'label', 'View Fit Results', 'callback', 'csafit(''view1'');');

  	QmatNMR.Q3 = uimenu(CSAFig, 'label', '   Plot Manipulations   ', 'position', [3]);
		uimenu(QmatNMR.Q3, 'label', 'Legend', 'callback', 'QezLegend', 'separator', 'on');
		QmatNMR.Q3Axis = uimenu(QmatNMR.Q3, 'label', 'Axis properties');
			uimenu(QmatNMR.Q3Axis, 'label', 'Axis On/Off/Etc', 'callback', 'askaxis');
			uimenu(QmatNMR.Q3Axis, 'label', 'Clear Axis', 'callback', 'askclearaxis');	
			uimenu(QmatNMR.Q3Axis, 'label', 'Axis Colors', 'callback', 'askaxiscolors');	
			uimenu(QmatNMR.Q3Axis, 'label', 'Axis Directions', 'callback', 'askdirs');	
			uimenu(QmatNMR.Q3Axis, 'label', 'Axis Labels', 'callback', 'askaxislabels');	
			uimenu(QmatNMR.Q3Axis, 'label', 'Axis Locations', 'callback', 'askaxislocation');	
			uimenu(QmatNMR.Q3Axis, 'label', 'Axis Position', 'callback', 'askaxisposition');
			uimenu(QmatNMR.Q3Axis, 'label', 'Axis View', 'callback', 'findcurrentfigure; askaxisview');
			uimenu(QmatNMR.Q3Axis, 'label', 'Title', 'callback', 'asktitle');
		uimenu(QmatNMR.Q3, 'label', 'Box', 'callback', 'askbox');
		uimenu(QmatNMR.Q3, 'label', 'Font Properties', 'callback', 'askfont');
		uimenu(QmatNMR.Q3, 'label', 'Grid', 'callback', 'askgrid');
		uimenu(QmatNMR.Q3, 'label', 'Hold', 'callback', 'askhold');
		QmatNMR.Q3Line = uimenu(QmatNMR.Q3, 'label', 'Line properties');
			QTEMP1= uimenu(QmatNMR.Q3Line, 'label', 'LineStyle');
				uimenu(QTEMP1,'label', '-', 'callback', 'Linestyle(''-''); disp(''Linestyle set to solid'');');
				uimenu(QTEMP1,'label', '--', 'callback', 'Linestyle(''--''); disp(''Linestyle set to dashed'');');
				uimenu(QTEMP1,'label', ':', 'callback', 'Linestyle('':''); disp(''Linestyle set to dotted'');');
				uimenu(QTEMP1,'label', '-.', 'callback', 'Linestyle(''-.''); disp(''Linestyle set to dash-dot'');');
				uimenu(QTEMP1,'label', 'None', 'callback', 'Linestyle(''none''); disp(''Linestyle set to none'');');
			QTEMP1 = uimenu(QmatNMR.Q3Line, 'label', 'LineWidth');
				uimenu(QTEMP1, 'label', '0.05', 'callback', 'Linewidth(0.05); disp(''Linewidth set to 0.05'');');	
				uimenu(QTEMP1, 'label', '0.10', 'callback', 'Linewidth(0.1); disp(''Linewidth set to 0.10'');');	
				uimenu(QTEMP1, 'label', '0.15', 'callback', 'Linewidth(0.15); disp(''Linewidth set to 0.15'');');	
				uimenu(QTEMP1, 'label', '0.25', 'callback', 'Linewidth(0.25); disp(''Linewidth set to 0.25'');');	
				uimenu(QTEMP1, 'label', '0.5', 'callback', 'Linewidth(0.5); disp(''Linewidth set to 0.5'');');	
				uimenu(QTEMP1, 'label', '1.0', 'callback', 'Linewidth(1.0); disp(''Linewidth set to 1.0'');');	
				uimenu(QTEMP1, 'label', '1.5', 'callback', 'Linewidth(1.5); disp(''Linewidth set to 1.5'');');	
				uimenu(QTEMP1, 'label', '2.0', 'callback', 'Linewidth(2.0); disp(''Linewidth set to 2.0'');');	
				uimenu(QTEMP1, 'label', '3.0', 'callback', 'Linewidth(3.0); disp(''Linewidth set to 3.0'');');	
				uimenu(QTEMP1, 'label', '4.0', 'callback', 'Linewidth(4.0); disp(''Linewidth set to 4.0'');');	
				uimenu(QTEMP1, 'label', '5.0', 'callback', 'Linewidth(5.0); disp(''Linewidth set to 5.0'');');	
				uimenu(QTEMP1, 'label', '6.0', 'callback', 'Linewidth(6.0); disp(''Linewidth set to 6.0'');');	
				uimenu(QTEMP1, 'label', '7.0', 'callback', 'Linewidth(7.0); disp(''Linewidth set to 7.0'');');	
				uimenu(QTEMP1, 'label', '8.0', 'callback', 'Linewidth(8.0); disp(''Linewidth set to 8.0'');');	
				uimenu(QTEMP1, 'label', '9.0', 'callback', 'Linewidth(9.0); disp(''Linewidth set to 9.0'');');	
				uimenu(QTEMP1, 'label', '10.0', 'callback', 'Linewidth(10.0); disp(''Linewidth set to 10.0'');');	
			QTEMP1= uimenu(QmatNMR.Q3Line, 'label', 'Marker');
				uimenu(QTEMP1,'label', 'None', 'callback', 'Marker(''none''); disp(''Marker set to none'');');
				uimenu(QTEMP1,'label', 'Point', 'callback', 'Marker(''.''); disp(''Marker set to point'');');
				uimenu(QTEMP1,'label', 'Plus', 'callback', 'Marker(''+''); disp(''Marker set to plus'');');
				uimenu(QTEMP1,'label', 'Circle', 'callback', 'Marker(''o''); disp(''Marker set to circle'');');
				uimenu(QTEMP1,'label', 'Asterisk', 'callback', 'Marker(''*''); disp(''Marker set to asterisk'');');
				uimenu(QTEMP1,'label', 'Cross', 'callback', 'Marker(''x''); disp(''Marker set to cross'');');
				uimenu(QTEMP1,'label', 'Square', 'callback', 'Marker(''s''); disp(''Marker set to square'');');
				uimenu(QTEMP1,'label', 'Diamond', 'callback', 'Marker(''d''); disp(''Marker set to triangle diamond'');');
				uimenu(QTEMP1,'label', 'Triangle up', 'callback', 'Marker(''^''); disp(''Marker set to triangle up'');');
				uimenu(QTEMP1,'label', 'Triangle down', 'callback', 'Marker(''v''); disp(''Marker set to triangle down'');');
				uimenu(QTEMP1,'label', 'Triangle right', 'callback', 'Marker(''>''); disp(''Marker set to triangle right'');');
				uimenu(QTEMP1,'label', 'Triangle left', 'callback', 'Marker(''<''); disp(''Marker set to triangle left'');');
				uimenu(QTEMP1,'label', 'Pentagram', 'callback', 'Marker(''p''); disp(''Marker set to pentagram'');');
				uimenu(QTEMP1,'label', 'Hexagram', 'callback', 'Marker(''h''); disp(''Marker set to hexagram'');');
			QTEMP1= uimenu(QmatNMR.Q3Line, 'label', 'Marker Size');
				uimenu(QTEMP1, 'label', '0.5', 'callback', 'Markersize(0.5); disp(''Marker Size set to 0.5'');');	
				uimenu(QTEMP1, 'label', '1.0', 'callback', 'Markersize(1.0); disp(''Marker Size set to 1.0'');');	
				uimenu(QTEMP1, 'label', '1.5', 'callback', 'Markersize(1.5); disp(''Marker Size set to 1.5'');');	
				uimenu(QTEMP1, 'label', '2.0', 'callback', 'Markersize(2.0); disp(''Marker Size set to 2.0'');');	
				uimenu(QTEMP1, 'label', '3.0', 'callback', 'Markersize(3.0); disp(''Marker Size set to 3.0'');');	
				uimenu(QTEMP1, 'label', '4.0', 'callback', 'Markersize(4.0); disp(''Marker Size set to 4.0'');');	
				uimenu(QTEMP1, 'label', '5.0', 'callback', 'Markersize(5.0); disp(''Marker Size set to 5.0'');');	
				uimenu(QTEMP1, 'label', '6.0', 'callback', 'Markersize(6.0); disp(''Marker Size set to 6.0'');');	
				uimenu(QTEMP1, 'label', '7.0', 'callback', 'Markersize(7.0); disp(''Marker Size set to 7.0'');');	
				uimenu(QTEMP1, 'label', '8.0', 'callback', 'Markersize(8.0); disp(''Marker Size set to 8.0'');');	
				uimenu(QTEMP1, 'label', '9.0', 'callback', 'Markersize(9.0); disp(''Marker Size set to 9.0'');');	
				uimenu(QTEMP1, 'label', '10.0', 'callback', 'Markersize(10.0); disp(''Marker Size set to 10.0'');');	
		uimenu(QmatNMR.Q3, 'label', 'Scaling Limits', 'callback', 'asklims');
		uimenu(QmatNMR.Q3, 'label', 'Scaling Types', 'callback', 'askscales');
		uimenu(QmatNMR.Q3, 'label', 'Shading', 'callback', 'askshading');
		QmatNMR.Q3Tick = uimenu(QmatNMR.Q3, 'label', 'Tick properties');
			uimenu(QmatNMR.Q3Tick, 'label', 'Tick direction', 'callback', 'asktickdir');
			uimenu(QmatNMR.Q3Tick, 'label', 'Tick Labels', 'callback', 'askticklabel');	
			uimenu(QmatNMR.Q3Tick, 'label', 'Tick Lengths', 'callback', 'askticklengths');	
			uimenu(QmatNMR.Q3Tick, 'label', 'Tick Positions', 'callback', 'asktick');

	QTEMP1 = uimenu(CSAFig, 'label', 'Macro', 'Position', [4]);
		uimenu(QTEMP1, 'label', 'Start Recording Macro', 'callback', 'QmatNMR.buttonList=1; QmatNMR.uiInput1=2; regelstartrecordingmacro', 'separator', 'on');
		uimenu(QTEMP1, 'label', 'Stop Recording Macro', 'callback', 'askstoprecordingmacro');
		uimenu(QTEMP1, 'label', 'Execute Macro', 'callback', 'QmatNMR.StepWise = 0; askexecutemacro', 'accelerator', 'e');
		uimenu(QTEMP1, 'label', 'Execute Macro Stepwise', 'callback', 'QmatNMR.StepWise = 1; askexecutemacro');

	QmatNMR.Q5 = uimenu('parent', CSAFig, 'label', '   Create Output   ', 'Position', [5]);
		uimenu(QmatNMR.Q5, 'label', 'Printing Menu', 'callback', 'figure(findobj(allchild(0),''tag'',''CSAFit'')); matprint;', 'accelerator', 'p');
		uimenu(QmatNMR.Q5, 'label', 'Save plot on disk', 'callback', 'asksavefitdisk');
  		uimenu(QmatNMR.Q5, 'label', 'Copy Figure', 'callback', 'figure(findobj(allchild(0),''tag'',''CSAFit'')); copyfignmr');

        QTEMP1 = uimenu('parent', CSAFig, 'label', '   HELP ?   ', 'position', [6]);
	  uimenu(QTEMP1, 'label', 'Copyright', 'callback', 'matnmrhelp(''Copyright.hlp'', ''Copyright'')');
 	  uimenu(QTEMP1, 'label', 'Help desk', 'callback', ['web file://' QmatNMR.HelpPath filesep 'manual' filesep 'index.html;']);

	QmatNMR.Q6 = uimenu('parent', CSAFig, 'label', '   Clear Functions   ', 'position', [7]);
		uimenu(QmatNMR.Q6, 'label', 'Clear Functions', 'callback', 'clear functions; disp(''Clear Functions performed ...''); Arrowhead');


	%
	%set the foreground colour of the uimenu according to the colour scheme
	%
	set(findobj(CSAFig, 'type', 'uimenu'), 'foregroundcolor', QmatNMR.ColorScheme.UImenuFore);



	%  Uicontrol Object Creation 
	
	stopbut = uicontrol('Style', 'Pushbutton', ...
		'Units', 'Pixels', ...
		'Position', [  5 200 110  50], ...
		'Units', 'Normalized', ...
		'String', 'Close', ...
		'BackGroundColor', QmatNMR.ColorScheme.Button3Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button3Fore, ...
		'Parent', CSAFig, ...
		'callback', 'askstopcsafit');
	        	
	simbut = uicontrol(... 
		'CallBack','csafit(''fitbut'');',... 
		'Units', 'Pixels', ...
		'Position', [  5 250 110  50], ...
		'Units', 'Normalized', ...
		'String','Simulate',... 
		'Style','pushbutton',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button4Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button4Fore, ...
		'Visible','on',... 
		'Parent', CSAFig, ...
		'UserData','simbut');
	        	
	fitbut = uicontrol(... 
		'CallBack','csafit(''fitbut'');',... 
		'Units', 'Pixels', ...
		'Position', [115 250 110  50], ...
		'Units', 'Normalized', ...
		'String','Fit',... 
		'Style','pushbutton',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button4Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button4Fore, ...
		'Visible','on',... 
		'Parent', CSAFig, ...
		'UserData','fitbut');
		
	refreshbut = uicontrol(... 
		'CallBack','csafit(''refreshbut'');',... 
		'Units', 'Pixels', ...
		'Position', [  5 300 110  50], ...
		'Units', 'Normalized', ...
		'String','Refresh',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button5Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button5Fore, ...
		'Visible','on',... 
		'Parent', CSAFig, ...
		'UserData','refreshbut');
		
				
	printbut = uicontrol('Style', 'PushButton', ...
		'Units', 'Pixels', ...
		'Position', [  5 350 110  50], ...
		'Units', 'Normalized', ...
		'String', 'Print', ...
		'BackGroundColor', QmatNMR.ColorScheme.Button6Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button6Fore, ...
		'Parent', CSAFig, ...
		'Callback', 'CSAprint');	
		


	zombut = uicontrol(... 
		'CallBack','csafit(''zombut'');',... 
		'Units', 'Pixels', ...
		'Position', [  5 660 120  35], ...
		'Units', 'Normalized', ...
		'String','Zoom',... 
                'value', 1, ...
		'Style','checkbox',... 
		'Visible','on',... 
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','zombut');  

	verbbut = uicontrol(... 
		'Units', 'Pixels', ...
		'Position', [125 660 100  35], ...
		'Units', 'Normalized', ...
		'String','Verbose | OFF | Iteration | Notify | Final',... 
		'Style','Popup',... 
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','verbbut');  

	TolButT = uicontrol('Style', 'PushButton', ...
		'Units', 'Pixels', ...
		'Position', [  5 625 120  35], ...
		'Units', 'Normalized', ...
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button7Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button7Fore, ...
		'String', 'Tolerance :');

	TolBut  = uicontrol('Style', 'Edit', ...
		'Units', 'Pixels', ...
		'Position', [125 625 100  35], ...
		'Units', 'Normalized', ...
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'String', '0.001');

	NrIterButT = uicontrol('Style', 'PushButton', ...
		'Units', 'Pixels', ...
		'Position', [  5 590 120  35], ...
		'Units', 'Normalized', ...
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button7Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button7Fore, ...
		'String', 'Max. Nr. Iter. :');

	NrIterBut = uicontrol('Style', 'Edit', ...
		'Units', 'Pixels', ...
		'Position', [125 590 100  35], ...
		'Units', 'Normalized', ...
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'String', '500');

	redisbutT = uicontrol('Style', 'PushButton', ...
		'Units', 'Pixels', ...
		'Position', [  5 555 120  35], ...
		'Units', 'Normalized', ...
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button7Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button7Fore, ...
		'String', 'Update display :');

	redisbut = uicontrol(... 
		'Units', 'Pixels', ...
		'Position', [125 555 100  35], ...
		'Units', 'Normalized', ...
		'String',' Off | Iteration',... 
		'Style','Popup',... 
		'CallBack','csafit(''redisbut'');',... 
		'Visible','on',...
                'Value', 2,... 
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','redisbut');  

	noibut = uicontrol(... 
		'Units', 'Pixels', ...
		'Position', [  5 500 120  35], ...
		'Units', 'Normalized', ...
		'String','Noise Level',... 
		'CallBack','csafit(''noibut'');',... 
		'Style','pushbutton',... 
		'Visible','on',... 
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','noibut');  

	noibute = uicontrol('Style', 'Edit', ...
		'Units', 'Pixels', ...
		'Position', [125 500 100  35], ...
		'Units', 'Normalized', ...
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'String', '1', ...
		'UserData','noibute');

	simplexbut = uicontrol('Style', 'PushButton', ...
		'Units', 'Pixels', ...
		'Position', [  5 465 220  35], ...
		'Units', 'Normalized', ...
		'Parent', CSAFig, ...
                'Style', 'Checkbox', ...
                'Value', 1, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'String', 'SIMPLEX Algorithm', ...
		'UserData','simplexbut');  

	gradbut = uicontrol('Style', 'PushButton', ...
		'Units', 'Pixels', ...
		'Position', [  5 430 220  35], ...
		'Units', 'Normalized', ...
		'Parent', CSAFig, ...
                'Style', 'Checkbox', ...
                'Value', 1, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'String', 'Gradient Algorithm', ...
		'UserData','gradbut');  



%
%Create 3 buttons in the main csafit window for the background level
%
		uicontrol('Style', 'PushButton', ...
		'Units', 'Pixels', ...
		'Position', [  5 130  100  35], ...
		'Units', 'Normalized', ...
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button7Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button7Fore, ...
		'String', 'Background :');

	ck(25) = uicontrol(... 
		'Units', 'Pixels', ...
		'Position', [  5  95  20  35], ...
		'Units', 'Normalized', ...
		'Style','checkbox',... 
                'Value', 1, ...
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','ck(25)'); 
	ed(25) = uicontrol(... 
		'Units', 'Pixels', ...
		'Position', [ 25  95  80  35], ...
		'Units', 'Normalized', ...
		'Style','edit',... 
		'Visible','on',... 
                'String', '0', ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','ed(25)'); 

%
%Create 3 buttons in the main csafit window for the slope of the background
%
		uicontrol('Style', 'PushButton', ...
		'Units', 'Pixels', ...
		'Position', [  5  40 100  35], ...
		'Units', 'Normalized', ...
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button7Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button7Fore, ...
		'String', 'Slope :');

	ck(26) = uicontrol(... 
		'Units', 'Pixels', ...
		'Position', [  5   5  20  35], ...
		'Units', 'Normalized', ...
		'Style','checkbox',... 
                'Value', 1, ...
		'Visible','on',... 
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','ck(26)'); 
	ed(26) = uicontrol(... 
		'Units', 'Pixels', ...
		'Position', [ 25   5  80  35], ...
		'Units', 'Normalized', ...
		'Style','edit',... 
		'Visible','on',... 
                'String', '0', ...
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','ed(26)'); 





%
%First create rows buttons with labels for the fit parameters
%
	  	uicontrol(... 
		'Units', 'Pixels', ...
		'Position', [120 145  55  35], ...
		'Units', 'Normalized', ...
		'Style','PushButton',... 
		'String','Symm?',... 
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button7Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button7Fore); 

	  	uicontrol(... 
		'Units', 'Pixels', ...
		'Position', [180 145 115  35], ...
		'Units', 'Normalized', ...
		'Style','PushButton',... 
		'String','Sigma 11',... 
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button7Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button7Fore); 

	  	uicontrol(... 
		'Units', 'Pixels', ...
		'Position', [300 145 115  35], ...
		'Units', 'Normalized', ...
		'Style','PushButton',... 
		'String','Sigma 22',... 
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button7Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button7Fore); 

	  	uicontrol(... 
		'Units', 'Pixels', ...
		'Position', [420 145 115  35], ...
		'Units', 'Normalized', ...
		'Style','PushButton',... 
		'String','sigma_33',... 
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button7Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button7Fore); 

	  	uicontrol(... 
		'Units', 'Pixels', ...
		'Position', [540 145 115  35], ...
		'Units', 'Normalized', ...
		'Style','PushButton',... 
		'String','Gaussian LB',... 
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button7Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button7Fore); 

	  	uicontrol(...
		'Units', 'Pixels', ...
		'Position', [660 145 115  35], ...
		'Units', 'Normalized', ...
		'Style','PushButton',... 
		'String','Lorentzian LB',... 
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button7Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button7Fore); 

	  	uicontrol(... 
		'Units', 'Pixels', ...
		'Position', [780 145 115  35], ...
		'Units', 'Normalized', ...
		'Style','PushButton',... 
		'String','Intensity',... 
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button7Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button7Fore); 





%
%First create 4 rows of 6 buttons and 6 check boxes in the main csafit window
%
        for tel=1:4
          %button for symmetric tensor
	  pop(tel) = uicontrol(... 
		'Units', 'Pixels', ...
		'Position', [120 110-(tel-1)*35  55  35], ...
		'Units', 'Normalized', ...
		'Style','Popup',... 
                'String', 'No | Yes', ...
                'Value', 1, ...
		'Visible','on',...
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'callback',['csafit(''pop(' num2str(tel) ')'')']); 

          %buttons for sigma_11
	  ck((tel-1)*6+1) = uicontrol(... 
		'Units', 'Pixels', ...
		'Position', [180 110-(tel-1)*35  20  35], ...
		'Units', 'Normalized', ...
		'Style','checkbox',... 
		'Visible','on',...
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['ck(' num2str((tel-1)*6+1) ')']); 
	  ed((tel-1)*6+1) = uicontrol(... 
		'Units', 'Pixels', ...
		'Position', [200 110-(tel-1)*35  95  35], ...
		'Units', 'Normalized', ...
		'Style','edit',... 
		'Visible','on',... 
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['ed(' num2str((tel-1)*6+1) ')']); 

          %buttons for sigma_22
	  ck((tel-1)*6+2) = uicontrol(... 
		'Units', 'Pixels', ...
		'Position', [300 110-(tel-1)*35  20  35], ...
		'Units', 'Normalized', ...
		'Style','checkbox',... 
		'Visible','on',...
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['ck(' num2str((tel-1)*6+2) ')']); 
	  ed((tel-1)*6+2) = uicontrol(... 
		'Units', 'Pixels', ...
		'Position', [320 110-(tel-1)*35  95  35], ...
		'Units', 'Normalized', ...
		'Style','edit',... 
		'Visible','on',... 
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['ed(' num2str((tel-1)*6+2) ')']); 

          %buttons for sigma_33
	  ck((tel-1)*6+3) = uicontrol(... 
		'Units', 'Pixels', ...
		'Position', [420 110-(tel-1)*35  20  35], ...
		'Units', 'Normalized', ...
		'Style','checkbox',... 
		'Visible','on',...
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['ck(' num2str((tel-1)*6+3) ')']); 
	  ed((tel-1)*6+3) = uicontrol(... 
		'Units', 'Pixels', ...
		'Position', [440 110-(tel-1)*35  95  35], ...
		'Units', 'Normalized', ...
		'Style','edit',... 
		'Visible','on',... 
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['ed(' num2str((tel-1)*6+3) ')']); 

          %buttons for Gaussian LB
	  ck((tel-1)*6+4) = uicontrol(... 
		'Units', 'Pixels', ...
		'Position', [540 110-(tel-1)*35  20  35], ...
		'Units', 'Normalized', ...
		'Style','checkbox',... 
                'Value', 1, ...
		'Visible','on',...
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['ck(' num2str((tel-1)*6+4) ')']); 
	  ed((tel-1)*6+4) = uicontrol(... 
		'Units', 'Pixels', ...
		'Position', [560 110-(tel-1)*35  95  35], ...
		'Units', 'Normalized', ...
		'Style','edit',... 
		'Visible','on',... 
                'String', '0', ...
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['ed(' num2str((tel-1)*6+4) ')']); 

          %buttons for Lorentzian LB
	  ck((tel-1)*6+5) = uicontrol(... 
		'Units', 'Pixels', ...
		'Position', [660 110-(tel-1)*35  20  35], ...
		'Units', 'Normalized', ...
		'Style','checkbox',... 
                'Value', 1, ...
		'Visible','on',...
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['ck(' num2str((tel-1)*6+5) ')']); 
	  ed((tel-1)*6+5) = uicontrol(... 
		'Units', 'Pixels', ...
		'Position', [680 110-(tel-1)*35  95  35], ...
		'Units', 'Normalized', ...
		'Style','edit',... 
		'Visible','on',... 
                'String', '0', ...
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['ed(' num2str((tel-1)*6+5) ')']); 

          %buttons for intensity
	  ck((tel-1)*6+6) = uicontrol(... 
		'Units', 'Pixels', ...
		'Position', [780 110-(tel-1)*35  20  35], ...
		'Units', 'Normalized', ...
		'Style','checkbox',... 
		'Visible','on',...
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['ck(' num2str((tel-1)*6+6) ')']); 
	  ed((tel-1)*6+6) = uicontrol(... 
		'Units', 'Pixels', ...
		'Position', [800 110-(tel-1)*35  95  35], ...
		'Units', 'Normalized', ...
		'Style','edit',... 
		'Visible','on',... 
		'Parent', CSAFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['ed(' num2str((tel-1)*6+6) ')']); 
	end	

	
%
%Save all these handles into the userdata property of the figure
%
        handle_list = [fitbut simbut ed ck pop TolBut NrIterBut noibut noibute zombut redisbut simplexbut gradbut refreshbut printbut stopbut verbbut];
        QTEMP.Handles = handle_list;
	set(findobj(allchild(gcf), 'type', 'uicontrol'), 'fontsize', QmatNMR.UIFontSize);
        delete(findobj(allchild(gcf), 'type', 'axes'));
	CSAFitAxis = axes('units', 'pixels', ...
	                 'position',[265 225 615 450], ...
			 'nextplot', 'replacechildren', ...
                         'XGrid','on', ...
			 'YGrid','on', ...
			 'FontSize', QmatNMR.TextSize, ...
			 'FontName', QmatNMR.TextFont, ...
			 'FontAngle', QmatNMR.TextAngle, ...
			 'FontWeight', QmatNMR.TextWeight, ...
			 'LineWidth', QmatNMR.LineWidth, ...
			 'visible','on', ...
			 'tag', 'CSAFitAxis', ...
			 'view', [0 90], ...
			 'visible', 'on', ...
			 'color', QmatNMR.ColorScheme.AxisBack, ...
			 'xcolor', QmatNMR.ColorScheme.AxisFore, ...
			 'ycolor', QmatNMR.ColorScheme.AxisFore, ...
			 'zcolor', QmatNMR.ColorScheme.AxisFore, ...
			 'xscale', 'linear', ...
			 'yscale', 'linear', ...
			 'zscale', 'linear', ...
			 'xtickmode', 'auto', ...
			 'ytickmode', 'auto', ...
			 'ztickmode', 'auto', ...
			 'xticklabelmode', 'auto', ...
			 'yticklabelmode', 'auto', ...
			 'zticklabelmode', 'auto', ...
			 'selected', 'off', ...
			 'userdata', 1, ...
			 'box', 'on');
	%
	%set the colours of the colour scheme also for the title
	%
	set(get(CSAFitAxis, 'title'), 'color', QmatNMR.ColorScheme.AxisFore);

	set(CSAFitAxis, 'units', 'normalized');
        %finally, set the size of the window to the user-defined values in normalized units
	set(CSAFig,'userdata',QTEMP, 'units', 'normalized', ...
                    'position', [QmatNMR.Q2D3DViewerLeft QmatNMR.Q2D3DViewerBottom QmatNMR.Q2D3DViewerWidth QmatNMR.Q2D3DViewerHeight], 'Visible', 'on');
