%
%
%
% matNMR v. 3.9.94 - A processing toolbox for NMR/EPR under MATLAB
%
% Copyright (c) 1997-2009  Jacco van Beek
% jabe@users.sourceforge.net
%
%
% This program is free software; you can redistribute it and/or
% modify it under the terms of the GNU General Public License
% as published by the Free Software Foundation; either version 2
% of the License, or (at your option) any later version.
% 
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with this program; if not, write to the Free Software
% Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
%
% --> gpl.txt
%
% Should yo be too lazy to do this, please remember:
%    - The code may be altered under the condition that all changes are clearly marked 
%      with your name and the date and that none of the names currently present in the 
%      code are removed.
%
% Furthermore:
%    -Please update the BugFixes.txt (i.e. the changelog file)!
%    -Please inform me of useful changes and annoying bugs!
%
% Jacco
%
%
% ====================================================================================
%
%
function pk_init;

% Initialize all the GUI controls for PEAKFIT
% 5-3-94 SMB (Bren@SLAC.stanford.edu)

%
% adapted for matNMR by Jacco van Beek
% 1-1-'97
%

global QmatNMR


%
%First create the additional window for having more than 4 peaks
%
        QmatNMR.ScreenSize = get(0, 'screensize');
	QTEMP = [];
	QTEMP.SubPlots = 1;
	PeakFig2 = figure('numbertitle','off',...
	       'Name','PEAKFIT -- Fitting Routine for Lorentzian/Gaussian Peaks',...
	       'units', 'pixels', ...
	       'position',[((QmatNMR.ScreenSize(3)-500)/2) ((QmatNMR.ScreenSize(4)-600)/2) 500 600],...
	       'backingstore', 'on', ...
	       'paperorientation', 'landscape', ...
         'papertype', 'a4letter', ....
	       'paperunits', 'normalized', ...
	       'paperposition', [0.1 0.1 .8 .8], ...
         'menubar', 'none', ...
         'visible', 'off', ...
	       'CloseRequestFCN', 'set(findobj(0, ''Tag'', ''Peakfit2''), ''visible'', ''off''); set(findobj(0, ''UserData'', ''morebut''), ''value'', 0)', ...
	       'userdata', QTEMP, ...
	       'color', QmatNMR.ColorScheme.Figure1Back, ...
	       'Tag', 'Peakfit2');
  if (QmatNMR.unittype == 1)
    set(PeakFig2, 'resize', 'on');
  else
    set(PeakFig2, 'resize', 'off');
  end

  %
  %To work around a Matlab bug (see BugFixes.txt, 11-05-'04) we redefine the position and units.
  %
  set(PeakFig2, 'units', 'pixels', 'position', [((QmatNMR.ScreenSize(3)-500)/2) ((QmatNMR.ScreenSize(4)-600)/2) 500 600]);

	set(gca, 'visible', 'off');
	set(PeakFig2, 'units', 'normalized');
	QTEMP1 = get(PeakFig2, 'Position');
	set(PeakFig2, 'Position', [QTEMP1(1) 0 QTEMP1(3:4)]);

    %
    %First create 32 rows of buttons in the main peakfit window
    %
        for tel=1:32
	  ck((tel+3)*4+1) = uicontrol(... 
		'Units','normalized',... 
		'Position',[ 0.00 1.0-tel*0.0312 0.048 0.0312 ],... 
		'Style','checkbox',... 
		'Visible','on',...
		'Parent', PeakFig2, ...
		'backgroundcolor', QmatNMR.ColorScheme.Button1Back, ...
		'foregroundcolor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['ck(' num2str((tel+3)*4+1) ')']); 
	  ed((tel+3)*4+1) = uicontrol(... 
		'Units','normalized',... 
		'Position',[ 0.048 1.0-tel*0.0312 0.176 0.0312 ],... 
		'Style','edit',... 
		'Units','normalized',... 
		'Visible','on',... 
		'Parent', PeakFig2, ...
		'backgroundcolor', QmatNMR.ColorScheme.Button1Back, ...
		'foregroundcolor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['ed(' num2str((tel+3)*4+1) ')']); 
	  rb((tel+3)*2+1) = uicontrol(... 
		'CallBack',['clearradios;'],... 
		'Units','normalized',... 
		'Position',[ 0.224 1.0-tel*0.0312 0.048 0.0312 ],... 
		'Style','radiobutton',... 
		'Visible','on',... 
		'Parent', PeakFig2, ...
		'backgroundcolor', QmatNMR.ColorScheme.Button1Back, ...
		'foregroundcolor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['rb(' num2str((tel+3)*2+1) ')']); 
	  ed((tel+3)*4+2) = uicontrol(... 
		'Units','normalized',... 
		'Position',[ 0.272 1.0-tel*0.0312 0.176 0.0312 ],... 
		'Style','edit',... 
		'Visible','on',... 
		'Parent', PeakFig2, ...
		'backgroundcolor', QmatNMR.ColorScheme.Button1Back, ...
		'foregroundcolor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['ed(' num2str((tel+3)*4+2) ')']); 
	  ck((tel+3)*4+2) = uicontrol(... 
		'Units','normalized',... 
		'Position',[ 0.448 1.0-tel*0.0312 0.048 0.0312 ],... 
		'Style','checkbox',... 
		'Visible','on',... 
		'Parent', PeakFig2, ...
		'backgroundcolor', QmatNMR.ColorScheme.Button1Back, ...
		'foregroundcolor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['ck(' num2str((tel+3)*4+2) ')']); 
	  ck((tel+3)*4+3) = uicontrol(... 
		'Units','normalized',... 
		'Position',[ 0.496 1.0-tel*0.0312 0.048 0.0312 ],... 
		'Style','checkbox',... 
		'Units','normalized',... 
		'Visible','on',... 
		'Parent', PeakFig2, ...
		'backgroundcolor', QmatNMR.ColorScheme.Button1Back, ...
		'foregroundcolor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['ck(' num2str((tel+3)*4+3) ')']); 
	  ed((tel+3)*4+3) = uicontrol(... 
		'Units','normalized',... 
		'Position',[ 0.544 1.0-tel*0.0312 0.176 0.0312 ],... 
		'Style','edit',... 
		'Units','normalized',... 
		'Visible','on',... 
		'Parent', PeakFig2, ...
		'backgroundcolor', QmatNMR.ColorScheme.Button1Back, ...
		'foregroundcolor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['ed(' num2str((tel+3)*4+3) ')']); 
	  rb((tel+4)*2) = uicontrol(... 
		'CallBack',['clearradios;'],... 
		'Units','normalized',... 
		'Position',[ 0.72 1.0-tel*0.0312 0.048 0.0312 ],... 
		'Style','radiobutton',... 
		'Visible','on',... 
		'Parent', PeakFig2, ...
		'backgroundcolor', QmatNMR.ColorScheme.Button1Back, ...
		'foregroundcolor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['rb(' num2str((tel+4)*2) ')']); 
	  ed((tel+4)*4) = uicontrol(... 
		'Units','normalized',... 
		'Position',[ 0.768 1.0-tel*0.0312 0.176 0.0312 ],... 
		'Style','edit',... 
		'Visible','on',... 
		'Parent', PeakFig2, ...
		'backgroundcolor', QmatNMR.ColorScheme.Button1Back, ...
		'foregroundcolor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['ed(' num2str((tel+4)*4) ')']); 
	  ck((tel+4)*4) = uicontrol(... 
		'Units','normalized',... 
		'Position',[ 0.944 1.0-tel*0.0312 0.048 0.0312 ],... 
		'Style','checkbox',... 
		'Visible','on',... 
		'Parent', PeakFig2, ...
		'backgroundcolor', QmatNMR.ColorScheme.Button1Back, ...
		'foregroundcolor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['ck(' num2str((tel+4)*4) ')']);
	end	


%
%Then the main window...
%
	PeakFig = figure('numbertitle','off',...
	       'Name','PEAKFIT -- Fitting Routine for Lorentzian/Gaussian Peaks',...
	       'position',[((QmatNMR.ScreenSize(3)-800)/2) ((QmatNMR.ScreenSize(4)-600)/2) 800 600],...
	       'backingstore', 'on', ...
	       'paperorientation', 'landscape', ...
         'papertype', 'a4letter', ....
	       'paperunits', 'normalized', ...
	       'paperposition', [0.1 0.1 .8 .8], ...
	       'CloseRequestFCN', 'stoppeakfit', ...
	       'color', QmatNMR.ColorScheme.Figure1Back, ...
         'menubar', 'none', ...
	       'Tag', 'Peakfit');
        if (QmatNMR.unittype == 1)
          set(PeakFig, 'resize', 'on');
        else
          set(PeakFig, 'resize', 'off');
        end
	set(gca, 'visible', 'off');

	%  Uimenubar Object Creation 

	QmatNMR.Q1 = uimenu('parent', PeakFig, 'label', '   Load parameters   ', 'Position', [1]);
		uimenu(QmatNMR.Q1, 'label', 'Load parameters', 'callback', 'peakfit(''loadpars1'');');

	QmatNMR.Q2 = uimenu('parent', PeakFig, 'label', '   View Fit Results   ', 'Position', [2]);
		uimenu(QmatNMR.Q2, 'label', 'Define Results Variable', 'callback', 'peakfit(''defvar1'');');
		uimenu(QmatNMR.Q2, 'label', 'View Fit Results', 'callback', 'peakfit(''view1'');');

  	QmatNMR.Q3 = uimenu(PeakFig, 'label', '   Plot Manipulations   ', 'position', [3]);
		uimenu(QmatNMR.Q3, 'label', 'Legend', 'callback', 'QezLegend', 'separator', 'on');
		QmatNMR.Q3Axis = uimenu(QmatNMR.Q3, 'label', 'Axis properties');
			uimenu(QmatNMR.Q3Axis, 'label', 'Axis On/Off/Etc', 'callback', 'askaxis');
			uimenu(QmatNMR.Q3Axis, 'label', 'Clear Axis', 'callback', 'askclearaxis');	
			uimenu(QmatNMR.Q3Axis, 'label', 'Axis Colors', 'callback', 'askaxiscolors');	
			uimenu(QmatNMR.Q3Axis, 'label', 'Axis Directions', 'callback', 'askdirs');	
			uimenu(QmatNMR.Q3Axis, 'label', 'Axis Labels', 'callback', 'askaxislabels');	
			uimenu(QmatNMR.Q3Axis, 'label', 'Axis Locations', 'callback', 'askaxislocation');	
			uimenu(QmatNMR.Q3Axis, 'label', 'Axis Position', 'callback', 'askaxisposition');
			uimenu(QmatNMR.Q3Axis, 'label', 'Axis View', 'callback', 'findcurrentfigure; askaxisview');
			uimenu(QmatNMR.Q3Axis, 'label', 'Title', 'callback', 'asktitle');
		uimenu(QmatNMR.Q3, 'label', 'Box', 'callback', 'askbox');
		uimenu(QmatNMR.Q3, 'label', 'Font Properties', 'callback', 'askfont');
		uimenu(QmatNMR.Q3, 'label', 'Grid', 'callback', 'askgrid');
		uimenu(QmatNMR.Q3, 'label', 'Hold', 'callback', 'askhold');
		QmatNMR.Q3Line = uimenu(QmatNMR.Q3, 'label', 'Line properties');
			QTEMP1= uimenu(QmatNMR.Q3Line, 'label', 'LineStyle');
				uimenu(QTEMP1,'label', '-', 'callback', 'Linestyle(''-''); disp(''Linestyle set to solid'');');
				uimenu(QTEMP1,'label', '--', 'callback', 'Linestyle(''--''); disp(''Linestyle set to dashed'');');
				uimenu(QTEMP1,'label', ':', 'callback', 'Linestyle('':''); disp(''Linestyle set to dotted'');');
				uimenu(QTEMP1,'label', '-.', 'callback', 'Linestyle(''-.''); disp(''Linestyle set to dash-dot'');');
				uimenu(QTEMP1,'label', 'None', 'callback', 'Linestyle(''none''); disp(''Linestyle set to none'');');
			QTEMP1 = uimenu(QmatNMR.Q3Line, 'label', 'LineWidth');
				uimenu(QTEMP1, 'label', '0.05', 'callback', 'Linewidth(0.05); disp(''Linewidth set to 0.05'');');	
				uimenu(QTEMP1, 'label', '0.10', 'callback', 'Linewidth(0.1); disp(''Linewidth set to 0.10'');');	
				uimenu(QTEMP1, 'label', '0.15', 'callback', 'Linewidth(0.15); disp(''Linewidth set to 0.15'');');	
				uimenu(QTEMP1, 'label', '0.25', 'callback', 'Linewidth(0.25); disp(''Linewidth set to 0.25'');');	
				uimenu(QTEMP1, 'label', '0.5', 'callback', 'Linewidth(0.5); disp(''Linewidth set to 0.5'');');	
				uimenu(QTEMP1, 'label', '1.0', 'callback', 'Linewidth(1.0); disp(''Linewidth set to 1.0'');');	
				uimenu(QTEMP1, 'label', '1.5', 'callback', 'Linewidth(1.5); disp(''Linewidth set to 1.5'');');	
				uimenu(QTEMP1, 'label', '2.0', 'callback', 'Linewidth(2.0); disp(''Linewidth set to 2.0'');');	
				uimenu(QTEMP1, 'label', '3.0', 'callback', 'Linewidth(3.0); disp(''Linewidth set to 3.0'');');	
				uimenu(QTEMP1, 'label', '4.0', 'callback', 'Linewidth(4.0); disp(''Linewidth set to 4.0'');');	
				uimenu(QTEMP1, 'label', '5.0', 'callback', 'Linewidth(5.0); disp(''Linewidth set to 5.0'');');	
				uimenu(QTEMP1, 'label', '6.0', 'callback', 'Linewidth(6.0); disp(''Linewidth set to 6.0'');');	
				uimenu(QTEMP1, 'label', '7.0', 'callback', 'Linewidth(7.0); disp(''Linewidth set to 7.0'');');	
				uimenu(QTEMP1, 'label', '8.0', 'callback', 'Linewidth(8.0); disp(''Linewidth set to 8.0'');');	
				uimenu(QTEMP1, 'label', '9.0', 'callback', 'Linewidth(9.0); disp(''Linewidth set to 9.0'');');	
				uimenu(QTEMP1, 'label', '10.0', 'callback', 'Linewidth(10.0); disp(''Linewidth set to 10.0'');');	
			QTEMP1= uimenu(QmatNMR.Q3Line, 'label', 'Marker');
				uimenu(QTEMP1,'label', 'None', 'callback', 'Marker(''none''); disp(''Marker set to none'');');
				uimenu(QTEMP1,'label', 'Point', 'callback', 'Marker(''.''); disp(''Marker set to point'');');
				uimenu(QTEMP1,'label', 'Plus', 'callback', 'Marker(''+''); disp(''Marker set to plus'');');
				uimenu(QTEMP1,'label', 'Circle', 'callback', 'Marker(''o''); disp(''Marker set to circle'');');
				uimenu(QTEMP1,'label', 'Asterisk', 'callback', 'Marker(''*''); disp(''Marker set to asterisk'');');
				uimenu(QTEMP1,'label', 'Cross', 'callback', 'Marker(''x''); disp(''Marker set to cross'');');
				uimenu(QTEMP1,'label', 'Square', 'callback', 'Marker(''s''); disp(''Marker set to square'');');
				uimenu(QTEMP1,'label', 'Diamond', 'callback', 'Marker(''d''); disp(''Marker set to triangle diamond'');');
				uimenu(QTEMP1,'label', 'Triangle up', 'callback', 'Marker(''^''); disp(''Marker set to triangle up'');');
				uimenu(QTEMP1,'label', 'Triangle down', 'callback', 'Marker(''v''); disp(''Marker set to triangle down'');');
				uimenu(QTEMP1,'label', 'Triangle right', 'callback', 'Marker(''>''); disp(''Marker set to triangle right'');');
				uimenu(QTEMP1,'label', 'Triangle left', 'callback', 'Marker(''<''); disp(''Marker set to triangle left'');');
				uimenu(QTEMP1,'label', 'Pentagram', 'callback', 'Marker(''p''); disp(''Marker set to pentagram'');');
				uimenu(QTEMP1,'label', 'Hexagram', 'callback', 'Marker(''h''); disp(''Marker set to hexagram'');');
			QTEMP1= uimenu(QmatNMR.Q3Line, 'label', 'Marker Size');
				uimenu(QTEMP1, 'label', '0.5', 'callback', 'Markersize(0.5); disp(''Marker Size set to 0.5'');');	
				uimenu(QTEMP1, 'label', '1.0', 'callback', 'Markersize(1.0); disp(''Marker Size set to 1.0'');');	
				uimenu(QTEMP1, 'label', '1.5', 'callback', 'Markersize(1.5); disp(''Marker Size set to 1.5'');');	
				uimenu(QTEMP1, 'label', '2.0', 'callback', 'Markersize(2.0); disp(''Marker Size set to 2.0'');');	
				uimenu(QTEMP1, 'label', '3.0', 'callback', 'Markersize(3.0); disp(''Marker Size set to 3.0'');');	
				uimenu(QTEMP1, 'label', '4.0', 'callback', 'Markersize(4.0); disp(''Marker Size set to 4.0'');');	
				uimenu(QTEMP1, 'label', '5.0', 'callback', 'Markersize(5.0); disp(''Marker Size set to 5.0'');');	
				uimenu(QTEMP1, 'label', '6.0', 'callback', 'Markersize(6.0); disp(''Marker Size set to 6.0'');');	
				uimenu(QTEMP1, 'label', '7.0', 'callback', 'Markersize(7.0); disp(''Marker Size set to 7.0'');');	
				uimenu(QTEMP1, 'label', '8.0', 'callback', 'Markersize(8.0); disp(''Marker Size set to 8.0'');');	
				uimenu(QTEMP1, 'label', '9.0', 'callback', 'Markersize(9.0); disp(''Marker Size set to 9.0'');');	
				uimenu(QTEMP1, 'label', '10.0', 'callback', 'Markersize(10.0); disp(''Marker Size set to 10.0'');');	
		uimenu(QmatNMR.Q3, 'label', 'Scaling Limits', 'callback', 'asklims');
		uimenu(QmatNMR.Q3, 'label', 'Scaling Types', 'callback', 'askscales');
		uimenu(QmatNMR.Q3, 'label', 'Shading', 'callback', 'askshading');
		QmatNMR.Q3Tick = uimenu(QmatNMR.Q3, 'label', 'Tick properties');
			uimenu(QmatNMR.Q3Tick, 'label', 'Tick direction', 'callback', 'asktickdir');
			uimenu(QmatNMR.Q3Tick, 'label', 'Tick Labels', 'callback', 'askticklabel');	
			uimenu(QmatNMR.Q3Tick, 'label', 'Tick Lengths', 'callback', 'askticklengths');	
			uimenu(QmatNMR.Q3Tick, 'label', 'Tick Positions', 'callback', 'asktick');

	QTEMP1 = uimenu(PeakFig, 'label', 'Macro', 'Position', [4]);
		uimenu(QTEMP1, 'label', 'Start Recording Macro', 'callback', 'QmatNMR.buttonList=1; QmatNMR.uiInput1=2; regelstartrecordingmacro', 'separator', 'on');
		uimenu(QTEMP1, 'label', 'Stop Recording Macro', 'callback', 'askstoprecordingmacro');
		uimenu(QTEMP1, 'label', 'Execute Macro', 'callback', 'QmatNMR.StepWise = 0; askexecutemacro', 'accelerator', 'e');
		uimenu(QTEMP1, 'label', 'Execute Macro Stepwise', 'callback', 'QmatNMR.StepWise = 1; askexecutemacro');

	QmatNMR.Q5 = uimenu('parent', PeakFig, 'label', '   Create Output   ', 'Position', [5]);
		uimenu(QmatNMR.Q5, 'label', 'Printing Menu', 'callback', 'figure(findobj(allchild(0),''tag'',''Peakfit'')); matprint;', 'accelerator', 'p');
		uimenu(QmatNMR.Q5, 'label', 'Save plot on disk', 'callback', 'asksavefitdisk');
  		uimenu(QmatNMR.Q5, 'label', 'Copy Figure', 'callback', 'figure(findobj(allchild(0),''tag'',''Peakfit'')); copyfignmr');

        QTEMP1 = uimenu('parent', PeakFig, 'label', '   HELP ?   ', 'position', [6]);
	  uimenu(QTEMP1, 'label', 'Copyright', 'callback', 'matnmrhelp(''Copyright.hlp'', ''Copyright'')');
 	  uimenu(QTEMP1, 'label', 'Help desk', 'callback', ['web file://' QmatNMR.HelpPath filesep 'manual' filesep 'index.html;']);

	QmatNMR.Q6 = uimenu('parent', PeakFig, 'label', '   Clear Functions   ', 'position', [7]);
		uimenu(QmatNMR.Q6, 'label', 'Clear Functions', 'callback', 'clear functions; disp(''Clear Functions performed ...''); Arrowhead');


	%
	%set the foreground colour of the uimenu according to the colour scheme
	%
	set(findobj(PeakFig, 'type', 'uimenu'), 'foregroundcolor', QmatNMR.ColorScheme.UImenuFore);



	%  Uicontrol Object Creation 
	
	stopbut = uicontrol('Style', 'Pushbutton', ...
		'Units', 'Normalized', ...
		'Position', [0.0 0.0 .11 .08], ...
		'String', 'Close', ...
		'BackGroundColor', QmatNMR.ColorScheme.Button3Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button3Fore, ...
		'Parent', PeakFig, ...
		'callback', 'askstoppeakfit');
		
	TolBut  = uicontrol('Style', 'Edit', ...
		'Units', 'Normalized', ...
		'Position', [0.23 .11 .14 .05], ...
		'Parent', PeakFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'String', '0.001');
		
	NrIterBut = uicontrol('Style', 'Edit', ...
		'Units', 'Normalized', ...
		'Position', [0.23 .16 .14 .05], ...
		'Parent', PeakFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'String', '100');
	        	
	fitbut = uicontrol(... 
		'CallBack','peakfit(''fitbut'');',... 
		'Units','normalized',... 
		'Position',[ 0 0.08 0.11 0.08 ],... 
		'String','Fit',... 
		'Style','pushbutton',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button4Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button4Fore, ...
		'Visible','on',... 
		'Parent', PeakFig, ...
		'UserData','fitbut');
		
	refreshbut = uicontrol(... 
		'CallBack','peakfit(''refreshbut'');',... 
		'Units','normalized',... 
		'Position',[ 0 0.16 0.11 0.08 ],... 
		'String','Refresh | Current 1D | Entire 2D',... 
		'Style','Popup',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button5Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button5Fore, ...
		'Visible','on',... 
		'Parent', PeakFig, ...
		'UserData','refreshbut');
		
				
	printbut = uicontrol('Style', 'PushButton', ...
		'Units', 'Normalized', ...
		'Position', [0 0.24 .11 .08], ...
		'String', 'Print', ...
		'BackGroundColor', QmatNMR.ColorScheme.Button6Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button6Fore, ...
		'Parent', PeakFig, ...
		'Callback', 'peakprint');	


	noibut = uicontrol(... 
		'CallBack','peakfit(''noibut'');',... 
		'Units','normalized',... 
		'Position',[ 0 0.70 0.11 0.06 ],... 
		'String','Noise Level',... 
		'Style','pushbutton',... 
		'Visible','on',... 
		'Parent', PeakFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','noibut');  


	curbut = uicontrol(... 
		'CallBack','peakfit(''curbut'');',... 
		'Units','normalized',... 
		'Position',[ 0 0.34 0.11 0.06 ],... 
		'String','Cursor',... 
		'Style','pushbutton',... 
		'Units','normalized',... 
		'Visible','on',... 
		'Parent', PeakFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','curbut'); 


	zombut = uicontrol(... 
		'CallBack','peakfit(''zombut'');',... 
		'Units','normalized',... 
		'Position',[ 0 0.60 0.13 0.06 ],... 
		'String','Zoom',... 
                'value', 1, ...
		'Style','checkbox',... 
		'Visible','on',... 
		'Parent', PeakFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','zombut');  


	lijstbut = uicontrol(... 
		'CallBack','peakfit(''lijstbut'');',... 
		'Units','normalized',... 
		'Position',[ 0 0.54 0.13 0.06 ],... 
		'String','Ext. Output',... 
		'Style','checkbox',... 
		'Visible','on',... 
		'Parent', PeakFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','lijstbut');  

	parambut = uicontrol(... 
		'CallBack','peakfit(''parambut'');',... 
		'Units','normalized',... 
		'Position',[ 0 0.48 0.13 0.06 ],... 
		'String','Re-use pars.',... 
		'Style','checkbox',... 
		'Visible','on',... 
		'Parent', PeakFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','parambut');  

	morebut = uicontrol(... 
		'CallBack','peakfit(''morebut'');',... 
		'Units','normalized',... 
		'Position',[ 0 0.42 0.13 0.06 ],... 
		'String','More Peaks',... 
		'Style','checkbox',... 
		'Parent', PeakFig, ...
		'Visible','on',...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','morebut');

	redisbut = uicontrol(... 
		'CallBack','peakfit(''redisbut'');',... 
		'Units','normalized',... 
		'Position',[ 0.23 0.21 0.14 0.05 ],... 
		'String',' Off | 1 | 5 | 10 | 25 | 50 | 100 ',... 
		'Style','Popup',... 
		'Visible','on',...
                'Value', 2,... 
		'Parent', PeakFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','redisbut');  
		
	MinText	= uicontrol('Style', 'PushButton', ...
		'String', 'Min :', ...
		'Units', 'norm', ...
		'Parent', PeakFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'Position', [0 0.93 0.08 0.06]');
		
        [MinSlice, MinButs] = Qeditnum(PeakFig, 1, 10000, 1, 'INT_BT_BB',...
                'units','norm',...
                'pos', [0.08 0.93 0.05 0.06],...
                'style', 'edit', ...
                'callback', 'peakfit(''MinSlice'')', ...
                'UserData', 'MinSlice', ...
		'Parent', PeakFig);
	set(MinSlice, 'backgroundcolor', QmatNMR.ColorScheme.Button2Back, 'foregroundcolor', QmatNMR.ColorScheme.Button2Fore);
	set(MinButs, 'backgroundcolor', QmatNMR.ColorScheme.Button1Back, 'foregroundcolor', QmatNMR.ColorScheme.Button1Fore);
		
	MaxText	= uicontrol('Style', 'PushButton', ...
		'String', 'Max :', ...
		'Units', 'norm', ...
		'Parent', PeakFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'Position', [0 0.87 0.08 0.06]');
		
        [MaxSlice, MaxButs] = Qeditnum(PeakFig, 1, 10000, 1, 'INT_BT_BB',...
                'units','norm',...
                'pos', [0.08 0.87 0.05 0.06],...
                'style', 'edit', ...
                'callback', 'peakfit(''MaxSlice'')', ...
                'UserData', 'MaxSlice', ...
		'Parent', PeakFig);
	set(MaxSlice, 'backgroundcolor', QmatNMR.ColorScheme.Button2Back, 'foregroundcolor', QmatNMR.ColorScheme.Button2Fore);
	set(MaxButs, 'backgroundcolor', QmatNMR.ColorScheme.Button1Back, 'foregroundcolor', QmatNMR.ColorScheme.Button1Fore);
		
	ViewText = uicontrol('Style', 'PushButton', ...
		'String', 'View :', ...
		'Units', 'norm', ...
		'Parent', PeakFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'Position', [0 0.81 0.08 0.06]');

		
        [ViewSlice, ViewButs] = Qeditnum(PeakFig, 1, 10000, 1, 'INT_BT_BB',...
                'units','norm',...
                'pos', [0.08 0.81 0.05 0.06],...
                'style', 'edit', ...
                'callback', 'peakfit(''ViewSlice'')', ...
                'UserData', 'ViewSlice', ...
		'Parent', PeakFig);
	set(ViewSlice, 'backgroundcolor', QmatNMR.ColorScheme.Button2Back, 'foregroundcolor', QmatNMR.ColorScheme.Button2Fore);
	set(ViewButs, 'backgroundcolor', QmatNMR.ColorScheme.Button1Back, 'foregroundcolor', QmatNMR.ColorScheme.Button1Fore);
		
		
	frtxt(1) = uicontrol(... 
		'Units','normalized',... 
		'Position',[ 0.15 0.16 0.11 0.05 ],...
		'Style','text',... 
		'String','NoCursor',...
		'Units','normalized',... 
		'Visible','off',... 
		'Parent', PeakFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','frtxt(1)'); 

%
%Create 3 buttons in the main peakfit window for the slope of the background
%
	ck(146) = uicontrol(... 
		'Units','normalized',... 
		'Position',[ 0.20 0.01 0.03 0.05 ],... 
		'Style','checkbox',... 
		'Visible','on',... 
		'Parent', PeakFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','ck(146)'); 
	ed(146) = uicontrol(... 
		'Units','normalized',... 
		'Position',[ 0.23 0.01 0.11 0.05 ],... 
		'Style','edit',... 
		'Visible','on',... 
		'Parent', PeakFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','ed(146)'); 
	rb(74) = uicontrol(... 
		'CallBack','clearradios;',... 
		'Units','normalized',... 
		'Position',[ 0.34 0.01 0.03 0.05 ],... 
		'Style','radiobutton',... 
		'Visible','on',... 
		'Parent', PeakFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','rb(74)'); 

%
%Create 3 buttons in the main peakfit window for the background level
%
	rb(73) = uicontrol(... 
		'Units','normalized',... 
		'CallBack','clearradios;',... 
		'Position',[ 0.34 0.06 0.03 0.05 ],... 
		'Style','radiobutton',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','rb(73)'); 
	ed(145) = uicontrol(... 
		'Units','normalized',... 
		'Position',[ 0.23 0.06 0.11 0.05 ],... 
		'Style','edit',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','ed(145)'); 
	ck(145) = uicontrol(... 
		'Units','normalized',... 
		'Position',[ 0.20 0.06 0.03 0.05 ],... 
		'Style','checkbox',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','ck(145)'); 

%
%First create 4 rows of buttons in the main peakfit window
%
        for tel=1:4
	  ck((tel-1)*4+1) = uicontrol(... 
		'Units','normalized',... 
		'Position',[ 0.37 0.21-tel*0.05 0.03 0.05 ],... 
		'Style','checkbox',... 
		'Visible','on',...
		'Parent', PeakFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['ck(' num2str((tel-1)*4+1) ')']); 
	  ed((tel-1)*4+1) = uicontrol(... 
		'Units','normalized',... 
		'Position',[ 0.40 0.21-tel*0.05 0.11 0.05 ],... 
		'Style','edit',... 
		'Visible','on',... 
		'Parent', PeakFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['ed(' num2str((tel-1)*4+1) ')']); 
	  rb((tel-1)*2+1) = uicontrol(... 
		'CallBack',['clearradios;'],... 
		'Units','normalized',... 
		'Position',[ 0.51 0.21-tel*0.05 0.03 0.05 ],... 
		'Style','radiobutton',... 
		'Visible','on',... 
		'Parent', PeakFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['rb(' num2str((tel-1)*2+1) ')']); 
	  ed((tel-1)*4+2) = uicontrol(... 
		'Units','normalized',... 
		'Position',[ 0.54 0.21-tel*0.05 0.11 0.05 ],... 
		'Style','edit',... 
		'Visible','on',... 
		'Parent', PeakFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['ed(' num2str((tel-1)*4+2) ')']); 
	  ck((tel-1)*4+2) = uicontrol(... 
		'Units','normalized',... 
		'Position',[ 0.65 0.21-tel*0.05 0.03 0.05 ],... 
		'Style','checkbox',... 
		'Visible','on',... 
		'Parent', PeakFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['ck(' num2str((tel-1)*4+2) ')']); 
	  ck((tel-1)*4+3) = uicontrol(... 
		'Units','normalized',... 
		'Position',[ 0.68 0.21-tel*0.05 0.03 0.05 ],... 
		'Style','checkbox',... 
		'Visible','on',... 
		'Parent', PeakFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['ck(' num2str((tel-1)*4+3) ')']); 
	  ed((tel-1)*4+3) = uicontrol(... 
		'Units','normalized',... 
		'Position',[ 0.71 0.21-tel*0.05 0.11 0.05 ],... 
		'Style','edit',... 
		'Visible','on',... 
		'Parent', PeakFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['ed(' num2str((tel-1)*4+3) ')']); 
	  rb(tel*2) = uicontrol(... 
		'CallBack',['clearradios;'],... 
		'Units','normalized',... 
		'Position',[ 0.82 0.21-tel*0.05 0.03 0.05 ],... 
		'Style','radiobutton',... 
		'Visible','on',... 
		'Parent', PeakFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['rb(' num2str(tel*2) ')']); 
	  ed(tel*4) = uicontrol(... 
		'Units','normalized',... 
		'Position',[ 0.85 0.21-tel*0.05 0.11 0.05 ],... 
		'Style','edit',... 
		'Visible','on',... 
		'Parent', PeakFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['ed(' num2str(tel*4) ')']); 
	  ck(tel*4) = uicontrol(... 
		'Units','normalized',... 
		'Position',[ 0.96 0.21-tel*0.05 0.03 0.05 ],... 
		'Style','checkbox',... 
		'Visible','on',... 
		'Parent', PeakFig, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData',['ck(' num2str(tel*4) ')']);
	end	

	
%
%Save all these handles into the userdata property of the figure
%
	handle_ui_list = [fitbut curbut ed(1:146) ck(1:146) rb(1:74) ...
			 frtxt(1) TolBut NrIterBut noibut zombut redisbut lijstbut ...
			 MinSlice MaxSlice ViewSlice parambut morebut refreshbut printbut stopbut]; 

        troep_ui_list = [ViewText MaxText MinText ViewButs MaxButs MinButs];
	

	%  Text Object Creation 
	txt1 = uicontrol('parent', PeakFig, ... 				%position of peak
		'Units','normalized',... 
		'Position',[ 0.37 0.21 0.155 0.04 ],... 
		'Style','pushbutton',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button7Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button7Fore, ...
		'String','Position'); 
	txt2 = uicontrol('parent', PeakFig, ... 				%amplitude of peak
		'Units','normalized',... 
		'Position',[ 0.525 0.21 0.155 0.04 ],... 
		'Style','pushbutton',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button7Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button7Fore, ...
		'String','Amplitude'); 
	txt3 = uicontrol('parent', PeakFig, ... 				%peak width
		'Units','normalized',... 
		'Position',[ 0.68 0.21 0.155 0.04 ],... 
		'Style','pushbutton',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button7Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button7Fore, ...
		'String','Width'); 
	txt4 = uicontrol('parent', PeakFig, ... 				%peak shape
		'Units','normalized',... 
		'Position',[ 0.835 0.21 0.155 0.04 ],... 
		'Style','pushbutton',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button7Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button7Fore, ...
		'String','Fraction Lorentzian'); 
	txt5 = uicontrol('parent', PeakFig, ... 				%Background
		'Units','normalized',... 
		'Position',[ 0.12 0.06 0.08 0.05 ],... 
		'Style','pushbutton',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button7Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button7Fore, ...
		'String','Bgrnd'); 
	txt6 = uicontrol('parent', PeakFig, ... 				%Slope
		'Units','normalized',... 
		'Position',[ 0.12 0.01 0.08 0.05 ],... 
		'Style','pushbutton',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button7Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button7Fore, ...
		'String','Slope'); 
	txt7 = uicontrol('parent', PeakFig, ... 				%Tolerance
		'Units','normalized',... 
		'Position',[ 0.12 0.11 0.11 0.05 ],... 
		'Style','pushbutton',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button7Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button7Fore, ...
		'String','Tolerance'); 
	txt8 = uicontrol('parent', PeakFig, ... 				%Max. Nr Iter.
		'Units','normalized',... 
		'Position',[ 0.12 0.16 0.11 0.05 ],... 
		'Style','pushbutton',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button7Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button7Fore, ...
		'String','Max. Nr Iter.'); 
	txt9 = uicontrol('parent', PeakFig, ... 				%Redisplay no.
		'Units','normalized',... 
		'Position',[ 0.12 0.21 0.11 0.05 ],... 
		'Style','pushbutton',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button7Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button7Fore, ...
		'String','Redisplay no.');

	handle_txt_list = [txt1 txt2 txt3 txt4 txt5 txt6 txt7 txt8 txt9]; 
	handle_list = [handle_ui_list handle_txt_list troep_ui_list]; 
	QTEMP.Handles = handle_list;
	set(handle_list, 'fontsize', QmatNMR.UIFontSize);
	set(PeakFig,'userdata',QTEMP, 'units', 'normalized', ...
                    'position', [QmatNMR.Q2D3DViewerLeft QmatNMR.Q2D3DViewerBottom QmatNMR.Q2D3DViewerWidth QmatNMR.Q2D3DViewerHeight], 'Visible', 'on');

	PeakFitAxis=axes('units', 'normalized', ...
	                 'position',[0.18 0.32 .78 .65], ...
			 'nextplot', 'replacechildren', ...
                         'XGrid','on', ...
			 'YGrid','on', ...
			 'FontSize', QmatNMR.TextSize, ...
			 'FontName', QmatNMR.TextFont, ...
			 'FontAngle', QmatNMR.TextAngle, ...
			 'FontWeight', QmatNMR.TextWeight, ...
			 'LineWidth', QmatNMR.LineWidth, ...
			 'visible','on', ...
			 'tag', 'PeakFitAxis', ...
			 'view', [0 90], ...
			 'visible', 'on', ...
			 'color', QmatNMR.ColorScheme.AxisBack, ...
			 'xcolor', QmatNMR.ColorScheme.AxisFore, ...
			 'ycolor', QmatNMR.ColorScheme.AxisFore, ...
			 'zcolor', QmatNMR.ColorScheme.AxisFore, ...
			 'xscale', 'linear', ...
			 'yscale', 'linear', ...
			 'zscale', 'linear', ...
			 'xtickmode', 'auto', ...
			 'ytickmode', 'auto', ...
			 'ztickmode', 'auto', ...
			 'xticklabelmode', 'auto', ...
			 'yticklabelmode', 'auto', ...
			 'zticklabelmode', 'auto', ...
			 'selected', 'off', ...
			 'userdata', 1, ...
			 'box', 'on');
	%
	%set the colours of the colour scheme also for the title
	%
	set(get(PeakFitAxis, 'title'), 'color', QmatNMR.ColorScheme.AxisFore);
