%
%
%
% matNMR v. 3.9.94 - A processing toolbox for NMR/EPR under MATLAB
%
% Copyright (c) 1997-2009  Jacco van Beek
% jabe@users.sourceforge.net
%
%
% This program is free software; you can redistribute it and/or
% modify it under the terms of the GNU General Public License
% as published by the Free Software Foundation; either version 2
% of the License, or (at your option) any later version.
% 
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with this program; if not, write to the Free Software
% Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
%
% --> gpl.txt
%
% Should yo be too lazy to do this, please remember:
%    - The code may be altered under the condition that all changes are clearly marked 
%      with your name and the date and that none of the names currently present in the 
%      code are removed.
%
% Furthermore:
%    -Please update the BugFixes.txt (i.e. the changelog file)!
%    -Please inform me of useful changes and annoying bugs!
%
% Jacco
%
%
% ====================================================================================
%
%
function Qfileops(command)
%
% This routine changes the file properties for matNMR !!
%
%14-12-'07

global QmatNMR

if ((nargin < 1) & (QmatNMR.leginp6 == 0))		%If window does not exist make new one.
%
  QmatNMR.leginp6=figure('Color','k','NumberTitle','off', ...
  	'Name', 'File properties for matNMR',...
  	'Units','pixels',...
        'Menubar','none',...
	'color', QmatNMR.ColorScheme.Figure1Back, ...
	'Position', [820 100 285 150], ...
        'closerequestfcn', 'global QmatNMR; try; delete(QmatNMR.leginp6); end; QmatNMR.leginp6 = [];');

  %
  %To work around a Matlab bug (see BugFixes.txt, 11-05-'04) we redefine the position and units.
  %
  set(QmatNMR.leginp6, 'units', 'pixels', 'Position', [820 100 485 150]);

  AxisHandle = axes('units', 'Normalized', 'Position', [0 0 1 1]);
  axis off
  axis([0,1,0,1])
  

%=======
  
%Close button
  uicontrol('Parent',QmatNMR.leginp6,...
			'style','pushbutton',...
			'string','Close',...
			'units','Pixels',...
			'position',[5 2 80 35],...
			'units', 'normalized', ...
			'BackGroundColor', QmatNMR.ColorScheme.Button4Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button4Fore, ...
			'callback','global QmatNMR; try; delete(QmatNMR.leginp6); end; QmatNMR.leginp6 = [];');

%Execute button
  uicontrol('Parent',QmatNMR.leginp6,...
			'style','pushbutton',...
			'string','Execute',...
			'units','Pixels',...
			'position',[100 2 80 35],...
			'units', 'normalized', ...
			'BackGroundColor', QmatNMR.ColorScheme.Button5Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button5Fore, ...
			'callback','Qfileops(3)');

%Save button
  uicontrol('Parent',QmatNMR.leginp6,...
			'style','pushbutton',...
			'string','Save',...
			'units','Pixels',...
			'position',[200 2 80 35],...
			'units', 'normalized', ...
			'BackGroundColor', QmatNMR.ColorScheme.Button3Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button3Fore, ...
			'callback','Qfileops(2)');


%buttons for setting the file options	
  fileopbut1 = uicontrol('Parent', QmatNMR.leginp6, ...
  			'Style', 'Pushbutton', ...
			'units','Pixels',...
                        'Position', [  5 55 150  30], ...
			'units', 'normalized', ...
                        'String', 'Default directory :', ...
                        'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
                        'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore);

  fileopbut2 = uicontrol('Parent', QmatNMR.leginp6, ...
  			'Style', 'Edit', ...
			'units','Pixels',...
                        'Position', [161 55 325  30], ...
			'units', 'normalized', ...
                        'String', QmatNMR.DefaultDirectory, ...
                        'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
                        'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);

  fileopbut3 = uicontrol('Parent', QmatNMR.leginp6, ...
  			'Style', 'check', ...
			'units','Pixels',...
                        'Position', [  5 115 475  30], ...
			'units', 'normalized', ...
                        'String', 'Re-use last directory when looking for new data', ...
                        'value', QmatNMR.ReuseLastDirectory, ...
                        'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
                        'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore);

  fileopbut4 = uicontrol('Parent', QmatNMR.leginp6, ...
        'Style', 'Pushbutton', ...
      'units','Pixels',...
                        'Position', [  5 85 150  30], ...
      'units', 'normalized', ...
                        'String', 'Search profile :', ...
                        'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
                        'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore);

  fileopbut5 = uicontrol('Parent', QmatNMR.leginp6, ...
        'Style', 'Edit', ...
      'units','Pixels',...
                        'Position', [161 85 325  30], ...
      'units', 'normalized', ...
                        'String', QmatNMR.SearchProfile, ...
                        'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
                        'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);

                        
%
% Now save all button handles in the userdata
% 
  set(QmatNMR.leginp6, 'units', 'normalized', 'userdata', [fileopbut1 fileopbut2 fileopbut3 fileopbut4 fileopbut5]);
  figure(QmatNMR.leginp6);

elseif ((nargin < 1) & (QmatNMR.leginp6 > 0))			%Figure window already exists so pull to front
	figure(QmatNMR.leginp6)
	
elseif command==2					%save file options
  QmatNMR.handles = get(QmatNMR.leginp6, 'userdata');

  QmatNMR.DefaultDirectory = get(QmatNMR.handles(2), 'string');
  QmatNMR.ReuseLastDirectory = get(QmatNMR.handles(3), 'value');
  QmatNMR.SearchProfile = get(QmatNMR.handles(5), 'string');

  SetOptions(7)
  %then we save all options
  saveoptions
    
elseif command==3					%font list has been changed
  QmatNMR.handles = get(QmatNMR.leginp6, 'userdata');
  QmatNMR.DefaultDirectory = get(QmatNMR.handles(2), 'string');
  QmatNMR.ReuseLastDirectory = get(QmatNMR.handles(3), 'value');
  QmatNMR.SearchProfile = get(QmatNMR.handles(5), 'string');
end
