%
%
%
% matNMR v. 3.9.94 - A processing toolbox for NMR/EPR under MATLAB
%
% Copyright (c) 1997-2009  Jacco van Beek
% jabe@users.sourceforge.net
%
%
% This program is free software; you can redistribute it and/or
% modify it under the terms of the GNU General Public License
% as published by the Free Software Foundation; either version 2
% of the License, or (at your option) any later version.
% 
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with this program; if not, write to the Free Software
% Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
%
% --> gpl.txt
%
% Should yo be too lazy to do this, please remember:
%    - The code may be altered under the condition that all changes are clearly marked 
%      with your name and the date and that none of the names currently present in the 
%      code are removed.
%
% Furthermore:
%    -Please update the BugFixes.txt (i.e. the changelog file)!
%    -Please inform me of useful changes and annoying bugs!
%
% Jacco
%
%
% ====================================================================================
%
%
function Qlinedata(command, Button)
%
% This routine changes the line properties of each newly drawn line for matNMR !!
%
% Jacco van Beek, june '97
%
%
% button were taken as in QezLegend.
%

global QmatNMR


if ((nargin < 1) & (QmatNMR.leginp == 0))		%If window does not exist make new one.
%
  T1=['-   ';'--  ';':   ';'-.  ';'none'];
  T2=['none     ';'.        ';'+        ';'o        ';'*        ';'x        ';'square   ';'diamond  ';'^        ';'v        ';'>        ';'<        ';'pentagram';'hexagram '];
  T3=['  Yellow  ';'   Cyan   ';'  Magenta ';'  Green   ';'   Red    ';'   Blue   ';'  White   '; '  Black   '];
  T4=str2mat('0.5', '1.0', '2.0', '3.0', '4.0', '5.0', '6.0', '7.0', '8.0', '9.0', '10.0', '15.0', '20.0', '30.0');


  QmatNMR.leginp=figure('Color','k','NumberTitle','off','Name',...
	'Line Properties',...
  	'Units','Pixels',...
        'Menubar','none',...
	'Position',[820 100 285 102], ...
	'color', QmatNMR.ColorScheme.Figure1Back, ...
	'CloseRequestFCN','global QmatNMR; try; delete(QmatNMR.leginp); end; QmatNMR.leginp = [];');

  %
  %To work around a Matlab bug (see BugFixes.txt, 11-05-'04) we redefine the position and units.
  %
  set(QmatNMR.leginp, 'units', 'pixels', 'position', [820 100 285 102]);

  axes('units', 'Normalized', 'Position', [0 0 1 1]);
  axis off
  axis([0,1,0,1])
  

%=======
  
%Close button
  uicontrol('Parent',QmatNMR.leginp,...
			'style','pushbutton',...
			'string','Close',...
			'units','Pixels',...
			'position',[11 2 80 35],...
			'BackGroundColor', QmatNMR.ColorScheme.Button4Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button4Fore, ...
			'callback','global QmatNMR; try; delete(QmatNMR.leginp); end; QmatNMR.leginp = [];');

%Save button
  uicontrol('Parent',QmatNMR.leginp,...
			'style','pushbutton',...
			'string','Save',...
			'units','Pixels',...
			'position',[11 65 80 35],...
			'BackGroundColor', QmatNMR.ColorScheme.Button3Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button3Fore, ...
			'callback','Qlinedata(6)');

%LineStyle button  
  uicontrol('Parent',QmatNMR.leginp,...
			'Style', 'Pushbutton', ...
  			'Units', 'Pixels', ...
  			'Position', [ 95 81 90 20],...
  			'String', 'Linestyle :', ...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore, ...
  			'HorizontalAlignment', 'center');
  			
  mi(1) = uicontrol('Parent',QmatNMR.leginp,...
			'Style','Popup','Units','Pixels',...
			'Position',[185 81 100 20],...
			'String',T1,...
			'Visible','on',...
                        'HorizontalAlignment', 'left',...
			'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
			'CallBack','Qlinedata(1)');
			
  Ttmp=['- ';'--';': ';'-.';'  '];
  for teller=1:5
    if strcmp(deblank(Ttmp(teller, :)), deblank(QmatNMR.LineType))
      set(mi(1), 'value', teller);
    end
  end;    


%LineWidth button  
  uicontrol('Parent',QmatNMR.leginp,...
			'Style', 'Pushbutton', ...
  			'Units', 'Pixels', ...
  			'Position', [ 95 61 90 20],...
  			'String', 'Linewidth :', ...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore, ...
  			'HorizontalAlignment', 'center');
  			
  mi(4) = uicontrol('Parent',QmatNMR.leginp,...
			'Style','Popup','Units','Pixels',...
			'Position',[185 61 100 20],...
			'String',T4,...
			'Visible','on',...
                        'HorizontalAlignment', 'left',...
			'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
			'CallBack','Qlinedata(4)');

  for teller=1:14
    if ( str2num(T4(teller, :)) == QmatNMR.LineWidth )
      set(mi(4), 'value', teller);
    end
  end;    
			
  
%Marker button
  uicontrol('Parent',QmatNMR.leginp,...
			'Style', 'Pushbutton', ...
  			'Units', 'Pixels', ...
  			'Position', [ 95 41 90 20],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore, ...
 			'String', 'Marker :', ...
  			'HorizontalAlignment', 'center');
 
  mi(2) = uicontrol('Parent',QmatNMR.leginp,...
			'Style','Popup','Units','Pixels',...
			'Position',[185 41 100 20],...
			'String',T2,...
			'Visible','on',...
                        'HorizontalAlignment', 'left',...
			'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
			'CallBack','Qlinedata(2)');

  Ttmp=[' ';'.';'+';'o';'*';'x';'s';'d';'^';'v';'>';'<';'p';'h'];
  for teller=1:14
    if strcmp(Ttmp(teller), QmatNMR.MarkerType)
      set(mi(2), 'value', teller);
    end
  end;    


%MarkerSize button
  uicontrol('Parent',QmatNMR.leginp,...
			'Style', 'Pushbutton', ...
  			'Units', 'Pixels', ...
  			'Position', [ 95 21 90 20],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore, ...
 			'String', 'Marker Size :', ...
  			'HorizontalAlignment', 'center');
 
  mi(5) = uicontrol('Parent',QmatNMR.leginp,...
			'Style','Popup','Units','Pixels',...
			'Position',[185 21 100 20],...
			'String',T4,...
			'Visible','on',...
                        'HorizontalAlignment', 'left',...
			'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
			'CallBack','Qlinedata(5)');

  for teller=1:14
    if ( str2num(T4(teller, :)) == QmatNMR.MarkerSize )
      set(mi(5), 'value', teller);
    end
  end;    



%Color button
  uicontrol('Parent',QmatNMR.leginp,...
			'Style', 'Pushbutton', ...
  			'Units', 'Pixels', ...
  			'Position', [ 95 1 90 20],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore, ...
  			'String', 'Color :', ...
  			'HorizontalAlignment', 'center');

  mi(3) = uicontrol('Parent',QmatNMR.leginp,...
			'Style','Popup','Units','Pixels',...
			'Position',[185 1 100 20],...
			'String',T3,...
			'Visible','on',...
                        'HorizontalAlignment', 'left',...
			'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
			'CallBack','Qlinedata(3)');

  Ttmp=['y';'c';'m';'g';'r';'b';'w';'k'];
  for teller=1:7
    if strcmp(Ttmp(teller), QmatNMR.LineColor)
      set(mi(3), 'value', teller);
    end
  end;    

 
 
  set(QmatNMR.leginp, 'userdata', mi);
  figure(QmatNMR.leginp);

elseif ((nargin < 1) & (QmatNMR.leginp > 0))			%Figure window already exists so pull to front
	figure(QmatNMR.leginp)
	
elseif command==1	%linestyle
	T1=str2mat('-', '--', ': ','-.', ' ');
	QmatNMR.handles = get(gcf,'UserData');

        QmatNMR.LineType = deblank(T1(get(QmatNMR.handles(1),'Value'),:));
        QmatNMR.LineHandle = findobj(get(findobj(get(QmatNMR.Fig, 'children'), 'type', 'axes'), 'children'), 'type', 'line');
        if (strcmp(QmatNMR.LineType, ''))
          set(QmatNMR.LineHandle, 'LineStyle', 'none');
        else
          set(QmatNMR.LineHandle, 'LineStyle', QmatNMR.LineType);
        end  
        

elseif command==2	%marker
	T2=str2mat(' ','.','+','o','*','x','s','d','^','v','>','<','p','h');
        QmatNMR.handles = get(gcf,'UserData');

        QmatNMR.MarkerType = deblank(T2(get(QmatNMR.handles(2),'Value'),:));
        QmatNMR.LineHandle = findobj(get(findobj(get(QmatNMR.Fig, 'children'), 'type', 'axes'), 'children'), 'type', 'line');
        if (strcmp(QmatNMR.MarkerType, ''))
          set(QmatNMR.LineHandle, 'Marker', 'none');
        else
          set(QmatNMR.LineHandle, 'Marker', QmatNMR.MarkerType);
        end  


elseif command==3	%Line color
        T3=str2mat('y','c','m','g','r','b','w','k');
	QmatNMR.handles = get(gcf,'UserData');

        QmatNMR.LineColor = T3(get(QmatNMR.handles(3),'Value'),:);
	QmatNMR.ColorScheme.LineMain = QmatNMR.LineColor;
        QmatNMR.LineHandle = findobj(get(findobj(get(QmatNMR.Fig, 'children'), 'type', 'axes'), 'children'), 'type', 'line');
        set(QmatNMR.LineHandle, 'Color', QmatNMR.LineColor);
        

elseif command==4	%Linewidth
        T4=str2mat('0.5', '1.0', '2.0', '3.0', '4.0', '5.0', '6.0', '7.0', '8.0', '9.0', '10.0', '15.0', '20.0', '30.0');
	QmatNMR.handles = get(gcf,'UserData');

        QmatNMR.LineWidth = str2num(T4(get(QmatNMR.handles(4),'Value'),:));
        QmatNMR.LineHandle = findobj(get(findobj(get(QmatNMR.Fig, 'children'), 'type', 'axes'), 'children'), 'type', 'line');
        set(QmatNMR.LineHandle, 'linewidth', QmatNMR.LineWidth);
        

elseif command==5	%Marker size
        T4=str2mat('0.5', '1.0', '2.0', '3.0', '4.0', '5.0', '6.0', '7.0', '8.0', '9.0', '10.0', '15.0', '20.0', '30.0');
	QmatNMR.handles = get(gcf,'UserData');

        QmatNMR.MarkerSize = str2num(T4(get(QmatNMR.handles(5),'Value'),:));
        QmatNMR.LineHandle = findobj(get(findobj(get(QmatNMR.Fig, 'children'), 'type', 'axes'), 'children'), 'type', 'line');
        set(QmatNMR.LineHandle, 'markersize', QmatNMR.MarkerSize);
        

elseif command==6	%save settings into options file
        SetOptions(5)
        saveoptions

end
