%
%
%
% matNMR v. 3.9.94 - A processing toolbox for NMR/EPR under MATLAB
%
% Copyright (c) 1997-2009  Jacco van Beek
% jabe@users.sourceforge.net
%
%
% This program is free software; you can redistribute it and/or
% modify it under the terms of the GNU General Public License
% as published by the Free Software Foundation; either version 2
% of the License, or (at your option) any later version.
% 
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with this program; if not, write to the Free Software
% Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
%
% --> gpl.txt
%
% Should yo be too lazy to do this, please remember:
%    - The code may be altered under the condition that all changes are clearly marked 
%      with your name and the date and that none of the names currently present in the 
%      code are removed.
%
% Furthermore:
%    -Please update the BugFixes.txt (i.e. the changelog file)!
%    -Please inform me of useful changes and annoying bugs!
%
% Jacco
%
%
% ====================================================================================
%
%
function Qscreenops(command)
%
% This routine changes the screen settings for matNMR !!
%
% Jacco van Beek, december '97
%
%
% button styles were taken from QezLegend.
%

global QmatNMR QmatNMRsettings

if ((nargin < 1) & (QmatNMR.leginp3 == 0))		%If window does not exist make new one.
%
  QmatNMR.leginp3=figure('Color','k','NumberTitle','off', ...
  	'Name', 'Screen settings for matNMR',...
  	'Units','Pixels',...
        'Menubar','none',...
	'Position',[65 35 450 350], ...
	'color', QmatNMR.ColorScheme.Figure1Back, ...
	'CloseRequestFCN','global QmatNMR; try; delete(QmatNMR.leginp3); end; QmatNMR.leginp3 = [];');

  %
  %To work around a Matlab bug (see BugFixes.txt, 11-05-'04) we redefine the position and units.
  %
  set(QmatNMR.leginp3, 'units', 'pixels', 'position', [65 35 450 350]);

  AxisHandle = axes('units', 'Normalized', 'Position', [0 0 1 1]);
  axis off
  axis([0,1,0,1])
  

%=======
  
%Close button
  uicontrol('Parent',QmatNMR.leginp3,...
			'style','pushbutton',...
			'string','Close',...
			'units','Pixels',...
			'position',[5 2 80 35],...
			'BackGroundColor', QmatNMR.ColorScheme.Button4Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button4Fore, ...
			'callback','global QmatNMR; try; delete(QmatNMR.leginp3); end; QmatNMR.leginp3 = [];');

%Save button
  uicontrol('Parent',QmatNMR.leginp3,...
			'style','pushbutton',...
			'string','Save',...
			'units','Pixels',...
			'position',[5 50 80 35],...
			'BackGroundColor', QmatNMR.ColorScheme.Button3Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button3Fore, ...
			'callback','Qscreenops(7)');



%buttons for the 2D/3D Viewer Panel window  			
  uicontrol('Parent',QmatNMR.leginp3,...
			'Style', 'Pushbutton', ...
  			'Units', 'Pixels', ...
  			'Position', [110 105 90 20],...
  			'String', 'Left :', ...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore, ...
  			'HorizontalAlignment', 'center');

  mi(5) = uicontrol('Parent',QmatNMR.leginp3,...
			'Style','Edit','Units','Pixels',...
			'Position',[200 105 70 20],...
			'String', QmatNMR.Q2D3DViewerPanelLeft,...
			'Visible','on',...
                        'HorizontalAlignment', 'left',...
			'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
			'CallBack','Qscreenops(2)');

  uicontrol('Parent',QmatNMR.leginp3,...
			'Style', 'Pushbutton', ...
  			'Units', 'Pixels', ...
  			'Position', [110 85 90 20],...
  			'String', 'Bottom :', ...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore, ...
  			'HorizontalAlignment', 'center');
  			
  mi(6) = uicontrol('Parent',QmatNMR.leginp3,...
			'Style','Edit','Units','Pixels',...
			'Position',[200 85 70 20],...
			'String', QmatNMR.Q2D3DViewerPanelBottom,...
			'Visible','on',...
                        'HorizontalAlignment', 'left',...
			'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
			'CallBack','Qscreenops(2)');

  uicontrol('Parent',QmatNMR.leginp3,...
			'Style', 'Pushbutton', ...
  			'Units', 'Pixels', ...
  			'Position', [280 105 90 20],...
  			'String', 'Width :', ...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore, ...
  			'HorizontalAlignment', 'center');
  			
  mi(7) = uicontrol('Parent',QmatNMR.leginp3,...
			'Style','Edit','Units','Pixels',...
			'Position',[370 105 70 20],...
			'String', QmatNMR.Q2D3DViewerPanelWidth,...
			'Visible','on',...
                        'HorizontalAlignment', 'left',...
			'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
			'CallBack','Qscreenops(2)');

  uicontrol('Parent',QmatNMR.leginp3,...
			'Style', 'Pushbutton', ...
  			'Units', 'Pixels', ...
  			'Position', [280 85 90 20],...
  			'String', 'Height :', ...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore, ...
  			'HorizontalAlignment', 'center');
  			
  mi(8) = uicontrol('Parent',QmatNMR.leginp3,...
			'Style','Edit','Units','Pixels',...
			'Position',[370 85 70 20],...
			'String', QmatNMR.Q2D3DViewerPanelHeight,...
			'Visible','on',...
                        'HorizontalAlignment', 'left',...
			'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
			'CallBack','Qscreenops(2)');
			
  text('Parent',AxisHandle,...
		'BackGroundColor', QmatNMR.ColorScheme.Text1Back, ...
		'Color', QmatNMR.ColorScheme.Text1Fore, ...
		'EraseMode','normal',... 
		'units', 'pixels', ...
		'Position',[90 137 0],...
		'Fontweight', 'Bold', ...
		'FontSize', [16], ...
		'FontName', 'Helvetica', ...
		'Rotation',0 ,... 
		'String','2D/3D Viewer Panel :'); 


%buttons for the 2D/3D Viewer window  			
  uicontrol('Parent',QmatNMR.leginp3,...
			'Style', 'Pushbutton', ...
  			'Units', 'Pixels', ...
  			'Position', [110 189 90 20],...
  			'String', 'Left :', ...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore, ...
  			'HorizontalAlignment', 'center');

  mi(9) = uicontrol('Parent',QmatNMR.leginp3,...
			'Style','Edit','Units','Pixels',...
			'Position',[200 189 70 20],...
			'String', QmatNMR.Q2D3DViewerLeft,...
			'Visible','on',...
                        'HorizontalAlignment', 'left',...
			'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
			'CallBack','Qscreenops(3)');

  uicontrol('Parent',QmatNMR.leginp3,...
			'Style', 'Pushbutton', ...
  			'Units', 'Pixels', ...
  			'Position', [110 169 90 20],...
  			'String', 'Bottom :', ...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore, ...
  			'HorizontalAlignment', 'center');
  			
  mi(10) = uicontrol('Parent',QmatNMR.leginp3,...
			'Style','Edit','Units','Pixels',...
			'Position',[200 169 70 20],...
			'String', QmatNMR.Q2D3DViewerBottom,...
			'Visible','on',...
                        'HorizontalAlignment', 'left',...
			'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
			'CallBack','Qscreenops(3)');

  uicontrol('Parent',QmatNMR.leginp3,...
			'Style', 'Pushbutton', ...
  			'Units', 'Pixels', ...
  			'Position', [280 189 90 20],...
  			'String', 'Width :', ...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore, ...
  			'HorizontalAlignment', 'center');
  			
  mi(11) = uicontrol('Parent',QmatNMR.leginp3,...
			'Style','Edit','Units','Pixels',...
			'Position',[370 189 70 20],...
			'String', QmatNMR.Q2D3DViewerWidth,...
			'Visible','on',...
                        'HorizontalAlignment', 'left',...
			'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
			'CallBack','Qscreenops(3)');

  uicontrol('Parent',QmatNMR.leginp3,...
			'Style', 'Pushbutton', ...
  			'Units', 'Pixels', ...
  			'Position', [280 169 90 20],...
  			'String', 'Height :', ...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore, ...
  			'HorizontalAlignment', 'center');
  			
  mi(12) = uicontrol('Parent',QmatNMR.leginp3,...
			'Style','Edit','Units','Pixels',...
			'Position',[370 169 70 20],...
			'String', QmatNMR.Q2D3DViewerHeight,...
			'Visible','on',...
                        'HorizontalAlignment', 'left',...
			'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
			'CallBack','Qscreenops(3)');
			
  text('Parent',AxisHandle,...
		'BackGroundColor', QmatNMR.ColorScheme.Text1Back, ...
		'Color', QmatNMR.ColorScheme.Text1Fore, ...
		'EraseMode','normal',... 
		'units', 'pixels', ...
		'Position',[90 221 0],...
		'Fontweight', 'Bold', ...
		'FontSize', [16], ...
		'FontName', 'Helvetica', ...
		'Rotation',0 ,... 
		'String','2D/3D Viewer window :'); 


%buttons for the matNMR main window  			
  uicontrol('Parent',QmatNMR.leginp3,...
			'Style', 'Pushbutton', ...
  			'Units', 'Pixels', ...
  			'Position', [110 273 90 20],...
  			'String', 'Left :', ...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore, ...
  			'HorizontalAlignment', 'center');

  mi(13) = uicontrol('Parent',QmatNMR.leginp3,...
			'Style','Edit','Units','Pixels',...
			'Position',[200 273 70 20],...
			'String', QmatNMR.figLeftNorm,...
			'Visible','on',...
                        'HorizontalAlignment', 'left',...
			'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
			'CallBack','Qscreenops(4)');

  uicontrol('Parent',QmatNMR.leginp3,...
			'Style', 'Pushbutton', ...
  			'Units', 'Pixels', ...
  			'Position', [110 253 90 20],...
  			'String', 'Bottom :', ...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore, ...
  			'HorizontalAlignment', 'center');
  			
  mi(14) = uicontrol('Parent',QmatNMR.leginp3,...
			'Style','Edit','Units','Pixels',...
			'Position',[200 253 70 20],...
			'String', QmatNMR.figBottomNorm,...
			'Visible','on',...
                        'HorizontalAlignment', 'left',...
			'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
			'CallBack','Qscreenops(4)');

  uicontrol('Parent',QmatNMR.leginp3,...
			'Style', 'Pushbutton', ...
  			'Units', 'Pixels', ...
  			'Position', [280 273 90 20],...
  			'String', 'Width :', ...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore, ...
  			'HorizontalAlignment', 'center');
  			
  mi(15) = uicontrol('Parent',QmatNMR.leginp3,...
			'Style','Edit','Units','Pixels',...
			'Position',[370 273 70 20],...
			'String', QmatNMR.figWidthNorm,...
			'Visible','on',...
                        'HorizontalAlignment', 'left',...
			'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
			'CallBack','Qscreenops(4)');

  uicontrol('Parent',QmatNMR.leginp3,...
			'Style', 'Pushbutton', ...
  			'Units', 'Pixels', ...
  			'Position', [280 253 90 20],...
  			'String', 'Height :', ...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore, ...
  			'HorizontalAlignment', 'center');
  			
  mi(16) = uicontrol('Parent',QmatNMR.leginp3,...
			'Style','Edit','Units','Pixels',...
			'Position',[370 253 70 20],...
			'String', QmatNMR.figHeightNorm,...
			'Visible','on',...
                        'HorizontalAlignment', 'left',...
			'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
			'CallBack','Qscreenops(4)');
			
  text('Parent',AxisHandle,...
		'BackGroundColor', QmatNMR.ColorScheme.Text1Back, ...
		'Color', QmatNMR.ColorScheme.Text1Fore, ...
		'EraseMode','normal',... 
		'units', 'pixels', ...
		'Position',[90 305 0],...
		'Fontweight', 'Bold', ...
		'FontSize', [16], ...
		'FontName', 'Helvetica', ...
		'Rotation',0 ,... 
		'String','matNMR main window :'); 
 

%
% Buttons to set flag for resizeable windows
%
  mi(17) = uicontrol('Parent',QmatNMR.leginp3, 'Style', 'check', 	'Position', [  1 322 180  28], 'String', 'Resizeable Window', 'callback', 'Qscreenops(5)');
  set(mi(17), 'value', QmatNMR.unittype);


%
% Buttons to set default font size for UIcontrols
%

  uicontrol('Parent',QmatNMR.leginp3,...
			'Style', 'Pushbutton', ...
  			'Units', 'Pixels', ...
  			'Position', [220 322 110 28],...
  			'String', 'UI Font Size :', ...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore, ...
  			'HorizontalAlignment', 'center');
  			
  mi(18) = uicontrol('Parent',QmatNMR.leginp3,...
			'Style','Edit','Units','Pixels',...
			'Position',[330 322 50 28],...
			'String', QmatNMR.UIFontSize,...
			'Visible','on',...
                        'HorizontalAlignment', 'center',...
			'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
			'CallBack','Qscreenops(6)');


%
% Now save all button QmatNMR.handles in the userdata
% 
  set(QmatNMR.leginp3, 'userdata', mi);
  figure(QmatNMR.leginp3);

elseif ((nargin < 1) & (QmatNMR.leginp3 > 0))			%Figure window already exists so pull to front
	figure(QmatNMR.leginp3)
	
elseif command==2
  QmatNMR.handles = get(QmatNMR.leginp3, 'userdata');

  QmatNMR.Q2D3DViewerPanelLeft 		= eval(get(QmatNMR.handles(5), 'String'));
  QmatNMR.Q2D3DViewerPanelBottom 	= eval(get(QmatNMR.handles(6), 'String'));
  QmatNMR.Q2D3DViewerPanelWidth 	= eval(get(QmatNMR.handles(7), 'String'));
  QmatNMR.Q2D3DViewerPanelHeight	= eval(get(QmatNMR.handles(8), 'String'));


  if ((QmatNMR.Q2DButtonPanel > 0) & (QmatNMR.unittype == 1))
    set(QmatNMR.Q2DButtonPanel, 'position', [QmatNMR.Q2D3DViewerPanelLeft QmatNMR.Q2D3DViewerPanelBottom QmatNMR.Q2D3DViewerPanelWidth QmatNMR.Q2D3DViewerPanelHeight]);
  end
    
elseif command==3
  QmatNMR.handles = get(QmatNMR.leginp3, 'userdata');

  QmatNMR.Q2D3DViewerLeft 	= eval(get(QmatNMR.handles(9), 'String'));
  QmatNMR.Q2D3DViewerBottom 	= eval(get(QmatNMR.handles(10), 'String'));
  QmatNMR.Q2D3DViewerWidth 	= eval(get(QmatNMR.handles(11), 'String'));
  QmatNMR.Q2D3DViewerHeight	= eval(get(QmatNMR.handles(12), 'String'));

  if ((QmatNMR.Fig2D3D > 0) & (QmatNMR.unittype == 1))
    QmatNMR.Ph = findobj(allchild(0),'tag','2D/3D Viewer');
    set(QmatNMR.Ph, 'position', [QmatNMR.Q2D3DViewerLeft QmatNMR.Q2D3DViewerBottom QmatNMR.Q2D3DViewerWidth QmatNMR.Q2D3DViewerHeight]);
  end
    
elseif command==4
  QmatNMR.handles = get(QmatNMR.leginp3, 'userdata');

  QmatNMR.figLeftNorm 		= eval(get(QmatNMR.handles(13), 'String'));
  QmatNMR.figBottomNorm	= eval(get(QmatNMR.handles(14), 'String'));
  QmatNMR.figWidthNorm 	= eval(get(QmatNMR.handles(15), 'String'));
  QmatNMR.figHeightNorm	= eval(get(QmatNMR.handles(16), 'String'));

  
  if ((QmatNMR.Fig > 0) & (QmatNMR.unittype == 1))
    QmatNMR.figLeft	= QmatNMR.figLeftNorm;		%These variables must be used to set a standard size for your
    QmatNMR.figBottom	= QmatNMR.figBottomNorm;	%screen. Change these inside nmr.m !!!
    QmatNMR.figWidth	= QmatNMR.figWidthNorm;
    QmatNMR.figHeight	= QmatNMR.figHeightNorm;

    set(QmatNMR.Fig, 'position', [QmatNMR.figLeft QmatNMR.figBottom QmatNMR.figWidth QmatNMR.figHeight]);
  end
  
elseif command==5
  watch;
  QmatNMR.handles = get(QmatNMR.leginp3, 'userdata');
  QmatNMR.unittype = get(QmatNMR.handles(17), 'Value');
  
  if ~isempty(QmatNMR.Fig)				%Change the size of the main window
    if (QmatNMR.unittype == 1)
      set(QmatNMR.Fig, 'resize', 'on');
    else
      set(QmatNMR.Fig, 'resize', 'off');
    end
  end
  
  if ~isempty(QmatNMR.Fig2D3D)			%change the size of the contours window
    QmatNMR.Ph = findobj(allchild(0),'tag','2D/3D Viewer');
    if (QmatNMR.unittype == 1)
      set(QmatNMR.Ph, 'resize', 'on');
    else
      set(QmatNMR.Ph, 'resize', 'off');
    end
  end
        
  figure(QmatNMR.leginp3);
  disp('All major matNMR windows currently openend have been changed ...');
  Arrowhead
    
elseif command == 6
  QmatNMR.handles = get(QmatNMR.leginp3, 'userdata');
  QmatNMR.UIFontSize = eval(get(QmatNMR.handles(18), 'String'));
  set(0, 'DefaultUIControlFontSize', QmatNMR.UIFontSize);
  
  disp(' ');
  disp('Default font size for UI-controls has been altered. Please Save and ');
  disp('restart matNMR to see the full effects of the change on your system.');
  disp('Continueing without restarting will cause all new windows to have the');
  disp('new font size, whereas all existing windows will not be updated.');
  disp(' ');
    
elseif command == 7 	%save settings into options file
  SetOptions(3)
  saveoptions
end
