%
%
%
% matNMR v. 3.9.94 - A processing toolbox for NMR/EPR under MATLAB
%
% Copyright (c) 1997-2009  Jacco van Beek
% jabe@users.sourceforge.net
%
%
% This program is free software; you can redistribute it and/or
% modify it under the terms of the GNU General Public License
% as published by the Free Software Foundation; either version 2
% of the License, or (at your option) any later version.
% 
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with this program; if not, write to the Free Software
% Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
%
% --> gpl.txt
%
% Should yo be too lazy to do this, please remember:
%    - The code may be altered under the condition that all changes are clearly marked 
%      with your name and the date and that none of the names currently present in the 
%      code are removed.
%
% Furthermore:
%    -Please update the BugFixes.txt (i.e. the changelog file)!
%    -Please inform me of useful changes and annoying bugs!
%
% Jacco
%
%
% ====================================================================================
%
%
function Qsetcolorscheme(command, command2)
%
% This routine changes the coliur scheme settings for matNMR !!
%
% Jacco van Beek, janurary 2005
%
%
% button styles were taken from QezLegend.
%

global QmatNMR QmatNMRsettings

if ((nargin < 1) & (QmatNMR.leginp5 == 0))		%If window does not exist make new one.
%
  windowwidth = 850;
  windowheight = 950;
  QmatNMR.leginp5=figure('Color','k','NumberTitle','off', ...
  	'Name', 'Colour scheme settings for matNMR',...
  	'Units','Pixels',...
        'Menubar','none',...
	'Position',[65  5 windowwidth windowheight], ...
	'color', QmatNMR.ColorScheme.Figure1Back, ...
	'CloseRequestFCN','global QmatNMR; try; delete(QmatNMR.leginp5); end; QmatNMR.leginp5 = [];');

  %
  %To work around a Matlab bug (see BugFixes.txt, 11-05-'04) we redefine the position and units.
  %
  set(QmatNMR.leginp5, 'units', 'pixels', 'position', [65  5 850 windowheight]);

  AxisHandle = axes('units', 'Normalized', 'Position', [0 0 1 1]);
  axis off
  axis([0,1,0,1])
  

%=======
  
%Close button
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'string','Close',...
			'units','Pixels',...
			'position',[5 2 100 35],...
			'BackGroundColor', QmatNMR.ColorScheme.Button4Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button4Fore, ...
			'callback','global QmatNMR; try; delete(QmatNMR.leginp5); end; QmatNMR.leginp5 = [];');

%Save button
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'string','Save',...
			'units','Pixels',...
			'position',[135 2 100 35],...
			'BackGroundColor', QmatNMR.ColorScheme.Button3Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button3Fore, ...
			'callback','Qsetcolorscheme(6)');

%Predefined schemes button
  Predefined = uicontrol('Parent',QmatNMR.leginp5,...
			'style','popup',...
			'string','Predefined Schemes | Default | Classic | Boring Grey | Psycho Red | Blue Gene',...
			'units','Pixels',...
			'position',[270 2 200 35],...
			'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
			'callback','Qsetcolorscheme(2)');

%
%create an array of buttons to show all the values in the colour scheme
%
  counter = 0;
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','text',...
			'string','Name',...
			'units','Pixels',...
			'position',[10 windowheight-35-(counter*33) 100 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','text',...
			'string','Details',...
			'units','Pixels',...
			'position',[110 windowheight-35-(counter*33) 200 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','text',...
			'units','Pixels',...
			'string', 'Values Background',...
			'position',[330 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','text',...
			'units','Pixels',...
			'string', 'Values Foreground',...
			'position',[501 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','text',...
			'units','Pixels',...
			'string', 'Results',...
			'position',[685 windowheight-35-(counter*33) 155 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);

  mi = [];
  
  %
  %Frame 1
  %
  counter = 1;
  NameString = 'Frame 1';
  DetailsString = 'background only';
  Back = QmatNMR.ColorScheme.Frame1;
  if isstr(Back)
    BackString = Back;
    Back = QmatNMR.ColorScheme.Figure1Back;
  else
    BackString = sprintf('[%0.4f %0.4f %0.4f]', Back);
  end
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'string',NameString,...
			'units','Pixels',...
			'position',[10 windowheight-35-(counter*33) 100 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','text',...
			'string', DetailsString,...
			'units','Pixels',...
			'position',[110 windowheight-35-(counter*33) 200 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  mi((counter-1)*3+1) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', BackString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[330 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+3) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'units','Pixels',...
			'string', '',...
			'position',[685 windowheight-35-(counter*33) 155 28],...
			'BackGroundColor', Back);
  
  %
  %Frame 2
  %
  counter = 2;
  NameString = 'Frame 2';
  DetailsString = 'background only';
  Back = QmatNMR.ColorScheme.Frame2;
  if isstr(Back)
    BackString = Back;
    Back = QmatNMR.ColorScheme.Figure1Back;
  else
    BackString = sprintf('[%0.4f %0.4f %0.4f]', Back);
  end
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'string',NameString,...
			'units','Pixels',...
			'position',[10 windowheight-35-(counter*33) 100 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','text',...
			'string', DetailsString,...
			'units','Pixels',...
			'position',[110 windowheight-35-(counter*33) 200 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  mi((counter-1)*3+1) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', BackString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[330 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+3) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'units','Pixels',...
			'string', '',...
			'position',[685 windowheight-35-(counter*33) 155 28],...
			'BackGroundColor', Back);
  
  %
  %Figure 1
  %
  counter = 3;
  NameString = 'Figure 1';
  DetailsString = 'most windows';
  Back = QmatNMR.ColorScheme.Figure1Back;
  if isstr(Back)
    BackString = Back;
    Back = QmatNMR.ColorScheme.Figure1Back;
  else
    BackString = sprintf('[%0.4f %0.4f %0.4f]', Back);
  end
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'string',NameString,...
			'units','Pixels',...
			'position',[10 windowheight-35-(counter*33) 100 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','text',...
			'string', DetailsString,...
			'units','Pixels',...
			'position',[110 windowheight-35-(counter*33) 200 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  mi((counter-1)*3+1) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', BackString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[330 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+3) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'units','Pixels',...
			'string', '',...
			'position',[685 windowheight-35-(counter*33) 155 28],...
			'BackGroundColor', Back);
  
  %
  %Figure 2
  %
  counter = 4;
  NameString = 'Figure 2';
  DetailsString = 'input windows';
  Back = QmatNMR.ColorScheme.Figure2Back;
  if isstr(Back)
    BackString = Back;
    Back = QmatNMR.ColorScheme.Figure1Back;
  else
    BackString = sprintf('[%0.4f %0.4f %0.4f]', Back);
  end
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'string',NameString,...
			'units','Pixels',...
			'position',[10 windowheight-35-(counter*33) 100 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','text',...
			'string', DetailsString,...
			'units','Pixels',...
			'position',[110 windowheight-35-(counter*33) 200 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  mi((counter-1)*3+1) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', BackString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[330 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+3) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'units','Pixels',...
			'string', '',...
			'position',[685 windowheight-35-(counter*33) 155 28],...
			'BackGroundColor', Back);
  
  %
  %UImenu foreground colours
  %
  counter = 5;
  NameString = 'UImenu';
  DetailsString = 'foreground only';

  Fore = QmatNMR.ColorScheme.UImenuFore;
  ForeString = sprintf('[%0.4f %0.4f %0.4f]', Fore);

  Back = [0.7 0.7 0.7];
  BackString = sprintf('[%0.4f %0.4f %0.4f]', Back);

  uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'string',NameString,...
			'units','Pixels',...
			'position',[10 windowheight-35-(counter*33) 100 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','text',...
			'string', DetailsString,...
			'units','Pixels',...
			'position',[110 windowheight-35-(counter*33) 200 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  mi((counter-1)*3+2) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', ForeString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[501 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+3) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'units','Pixels',...
			'string', 'test test',...
			'position',[685 windowheight-35-(counter*33) 155 28],...
			'BackGroundColor', Back,...
			'ForeGroundColor', Fore);
  
  %
  %Axes colours
  %
  counter = 6;
  NameString = 'Axes';
  DetailsString = 'foreground defines labels etc.';

  Fore = QmatNMR.ColorScheme.AxisFore;
  ForeString = sprintf('[%0.4f %0.4f %0.4f]', Fore);

  Back = QmatNMR.ColorScheme.AxisBack;
  if isstr(Back)
    BackString = Back;
    Back = QmatNMR.ColorScheme.Figure1Back;
  else
    BackString = sprintf('[%0.4f %0.4f %0.4f]', Back);
  end
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'string',NameString,...
			'units','Pixels',...
			'position',[10 windowheight-35-(counter*33) 100 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','text',...
			'string', DetailsString,...
			'units','Pixels',...
			'position',[110 windowheight-35-(counter*33) 200 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  mi((counter-1)*3+1) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', BackString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[330 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+2) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', ForeString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[501 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+3) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'units','Pixels',...
			'string', 'test test',...
			'position',[685 windowheight-35-(counter*33) 155 28],...
			'BackGroundColor', Back,...
			'ForeGroundColor', Fore);
  
  %
  %UIcontrol 1
  %
  counter = 7;
  NameString = 'UIcontrol 1';
  DetailsString = 'default UIcontrol';

  Fore = QmatNMR.ColorScheme.Button1Fore;
  ForeString = sprintf('[%0.4f %0.4f %0.4f]', Fore);

  Back = QmatNMR.ColorScheme.Button1Back;
  BackString = sprintf('[%0.4f %0.4f %0.4f]', Back);

  uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'string',NameString,...
			'units','Pixels',...
			'position',[10 windowheight-35-(counter*33) 100 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','text',...
			'string', DetailsString,...
			'units','Pixels',...
			'position',[110 windowheight-35-(counter*33) 200 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  mi((counter-1)*3+1) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', BackString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[330 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+2) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', ForeString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[501 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+3) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'units','Pixels',...
			'string', 'test test',...
			'position',[685 windowheight-35-(counter*33) 155 28],...
			'BackGroundColor', Back,...
			'ForeGroundColor', Fore);
  
  %
  %UIcontrol 2
  %
  counter = 8;
  NameString = 'UIcontrol 2';
  DetailsString = '';

  Fore = QmatNMR.ColorScheme.Button2Fore;
  ForeString = sprintf('[%0.4f %0.4f %0.4f]', Fore);

  Back = QmatNMR.ColorScheme.Button2Back;
  BackString = sprintf('[%0.4f %0.4f %0.4f]', Back);

  uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'string',NameString,...
			'units','Pixels',...
			'position',[10 windowheight-35-(counter*33) 100 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','text',...
			'string', DetailsString,...
			'units','Pixels',...
			'position',[110 windowheight-35-(counter*33) 200 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  mi((counter-1)*3+1) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', BackString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[330 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+2) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', ForeString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[501 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+3) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'units','Pixels',...
			'string', 'test test',...
			'position',[685 windowheight-35-(counter*33) 155 28],...
			'BackGroundColor', Back,...
			'ForeGroundColor', Fore);
  
  %
  %UIcontrol 3
  %
  counter = 9;
  NameString = 'UIcontrol 3';
  DetailsString = '';

  Fore = QmatNMR.ColorScheme.Button3Fore;
  ForeString = sprintf('[%0.4f %0.4f %0.4f]', Fore);

  Back = QmatNMR.ColorScheme.Button3Back;
  BackString = sprintf('[%0.4f %0.4f %0.4f]', Back);

  uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'string',NameString,...
			'units','Pixels',...
			'position',[10 windowheight-35-(counter*33) 100 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','text',...
			'string', DetailsString,...
			'units','Pixels',...
			'position',[110 windowheight-35-(counter*33) 200 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  mi((counter-1)*3+1) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', BackString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[330 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+2) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', ForeString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[501 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+3) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'units','Pixels',...
			'string', 'test test',...
			'position',[685 windowheight-35-(counter*33) 155 28],...
			'BackGroundColor', Back,...
			'ForeGroundColor', Fore);
  
  %
  %UIcontrol 4
  %
  counter = 10;
  NameString = 'UIcontrol 4';
  DetailsString = '';

  Fore = QmatNMR.ColorScheme.Button4Fore;
  ForeString = sprintf('[%0.4f %0.4f %0.4f]', Fore);

  Back = QmatNMR.ColorScheme.Button4Back;
  BackString = sprintf('[%0.4f %0.4f %0.4f]', Back);

  uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'string',NameString,...
			'units','Pixels',...
			'position',[10 windowheight-35-(counter*33) 100 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','text',...
			'string', DetailsString,...
			'units','Pixels',...
			'position',[110 windowheight-35-(counter*33) 200 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  mi((counter-1)*3+1) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', BackString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[330 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+2) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', ForeString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[501 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+3) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'units','Pixels',...
			'string', 'test test',...
			'position',[685 windowheight-35-(counter*33) 155 28],...
			'BackGroundColor', Back,...
			'ForeGroundColor', Fore);
  
  %
  %UIcontrol 5
  %
  counter = 11;
  NameString = 'UIcontrol 5';
  DetailsString = '';

  Fore = QmatNMR.ColorScheme.Button5Fore;
  ForeString = sprintf('[%0.4f %0.4f %0.4f]', Fore);

  Back = QmatNMR.ColorScheme.Button5Back;
  BackString = sprintf('[%0.4f %0.4f %0.4f]', Back);

  uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'string',NameString,...
			'units','Pixels',...
			'position',[10 windowheight-35-(counter*33) 100 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','text',...
			'string', DetailsString,...
			'units','Pixels',...
			'position',[110 windowheight-35-(counter*33) 200 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  mi((counter-1)*3+1) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', BackString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[330 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+2) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', ForeString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[501 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+3) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'units','Pixels',...
			'string', 'test test',...
			'position',[685 windowheight-35-(counter*33) 155 28],...
			'BackGroundColor', Back,...
			'ForeGroundColor', Fore);
  
  %
  %UIcontrol 6
  %
  counter = 12;
  NameString = 'UIcontrol 6';
  DetailsString = '';

  Fore = QmatNMR.ColorScheme.Button6Fore;
  ForeString = sprintf('[%0.4f %0.4f %0.4f]', Fore);

  Back = QmatNMR.ColorScheme.Button6Back;
  BackString = sprintf('[%0.4f %0.4f %0.4f]', Back);

  uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'string',NameString,...
			'units','Pixels',...
			'position',[10 windowheight-35-(counter*33) 100 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','text',...
			'string', DetailsString,...
			'units','Pixels',...
			'position',[110 windowheight-35-(counter*33) 200 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  mi((counter-1)*3+1) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', BackString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[330 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+2) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', ForeString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[501 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+3) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'units','Pixels',...
			'string', 'test test',...
			'position',[685 windowheight-35-(counter*33) 155 28],...
			'BackGroundColor', Back,...
			'ForeGroundColor', Fore);
  
  %
  %UIcontrol 7
  %
  counter = 13;
  NameString = 'UIcontrol 7';
  DetailsString = '';

  Fore = QmatNMR.ColorScheme.Button7Fore;
  ForeString = sprintf('[%0.4f %0.4f %0.4f]', Fore);

  Back = QmatNMR.ColorScheme.Button7Back;
  BackString = sprintf('[%0.4f %0.4f %0.4f]', Back);

  uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'string',NameString,...
			'units','Pixels',...
			'position',[10 windowheight-35-(counter*33) 100 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','text',...
			'string', DetailsString,...
			'units','Pixels',...
			'position',[110 windowheight-35-(counter*33) 200 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  mi((counter-1)*3+1) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', BackString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[330 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+2) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', ForeString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[501 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+3) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'units','Pixels',...
			'string', 'test test',...
			'position',[685 windowheight-35-(counter*33) 155 28],...
			'BackGroundColor', Back,...
			'ForeGroundColor', Fore);
  
  %
  %UIcontrol 8
  %
  counter = 14;
  NameString = 'UIcontrol 8';
  DetailsString = '';

  Fore = QmatNMR.ColorScheme.Button8Fore;
  ForeString = sprintf('[%0.4f %0.4f %0.4f]', Fore);

  Back = QmatNMR.ColorScheme.Button8Back;
  BackString = sprintf('[%0.4f %0.4f %0.4f]', Back);

  uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'string',NameString,...
			'units','Pixels',...
			'position',[10 windowheight-35-(counter*33) 100 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','text',...
			'string', DetailsString,...
			'units','Pixels',...
			'position',[110 windowheight-35-(counter*33) 200 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  mi((counter-1)*3+1) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', BackString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[330 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+2) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', ForeString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[501 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+3) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'units','Pixels',...
			'string', 'test test',...
			'position',[685 windowheight-35-(counter*33) 155 28],...
			'BackGroundColor', Back,...
			'ForeGroundColor', Fore);
  
  %
  %UIcontrol 9
  %
  counter = 15;
  NameString = 'UIcontrol 9';
  DetailsString = '';

  Fore = QmatNMR.ColorScheme.Button9Fore;
  ForeString = sprintf('[%0.4f %0.4f %0.4f]', Fore);

  Back = QmatNMR.ColorScheme.Button9Back;
  BackString = sprintf('[%0.4f %0.4f %0.4f]', Back);

  uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'string',NameString,...
			'units','Pixels',...
			'position',[10 windowheight-35-(counter*33) 100 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','text',...
			'string', DetailsString,...
			'units','Pixels',...
			'position',[110 windowheight-35-(counter*33) 200 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  mi((counter-1)*3+1) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', BackString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[330 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+2) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', ForeString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[501 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+3) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'units','Pixels',...
			'string', 'test test',...
			'position',[685 windowheight-35-(counter*33) 155 28],...
			'BackGroundColor', Back,...
			'ForeGroundColor', Fore);
  
  %
  %UIcontrol 10
  %
  counter = 16;
  NameString = 'UIcontrol 10';
  DetailsString = '';

  Fore = QmatNMR.ColorScheme.Button10Fore;
  ForeString = sprintf('[%0.4f %0.4f %0.4f]', Fore);

  Back = QmatNMR.ColorScheme.Button10Back;
  BackString = sprintf('[%0.4f %0.4f %0.4f]', Back);

  uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'string',NameString,...
			'units','Pixels',...
			'position',[10 windowheight-35-(counter*33) 100 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','text',...
			'string', DetailsString,...
			'units','Pixels',...
			'position',[110 windowheight-35-(counter*33) 200 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  mi((counter-1)*3+1) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', BackString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[330 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+2) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', ForeString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[501 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+3) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'units','Pixels',...
			'string', 'test test',...
			'position',[685 windowheight-35-(counter*33) 155 28],...
			'BackGroundColor', Back,...
			'ForeGroundColor', Fore);
  
  %
  %UIcontrol 11
  %
  counter = 17;
  NameString = 'UIcontrol 11';
  DetailsString = 'input windows';

  Fore = QmatNMR.ColorScheme.Button11Fore;
  ForeString = sprintf('[%0.4f %0.4f %0.4f]', Fore);

  Back = QmatNMR.ColorScheme.Button11Back;
  BackString = sprintf('[%0.4f %0.4f %0.4f]', Back);

  uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'string',NameString,...
			'units','Pixels',...
			'position',[10 windowheight-35-(counter*33) 100 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','text',...
			'string', DetailsString,...
			'units','Pixels',...
			'position',[110 windowheight-35-(counter*33) 200 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  mi((counter-1)*3+1) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', BackString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[330 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+2) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', ForeString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[501 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+3) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'units','Pixels',...
			'string', 'test test',...
			'position',[685 windowheight-35-(counter*33) 155 28],...
			'BackGroundColor', Back,...
			'ForeGroundColor', Fore);
  
  %
  %UIcontrol 12
  %
  counter = 18;
  NameString = 'UIcontrol 12';
  DetailsString = 'match background to figure 1';

  Fore = QmatNMR.ColorScheme.Button12Fore;
  ForeString = sprintf('[%0.4f %0.4f %0.4f]', Fore);

  Back = QmatNMR.ColorScheme.Button12Back;
  BackString = sprintf('[%0.4f %0.4f %0.4f]', Back);

  uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'string',NameString,...
			'units','Pixels',...
			'position',[10 windowheight-35-(counter*33) 100 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','text',...
			'string', DetailsString,...
			'units','Pixels',...
			'position',[110 windowheight-35-(counter*33) 200 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  mi((counter-1)*3+1) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', BackString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[330 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+2) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', ForeString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[501 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+3) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'units','Pixels',...
			'string', 'test test',...
			'position',[685 windowheight-35-(counter*33) 155 28],...
			'BackGroundColor', Back,...
			'ForeGroundColor', Fore);
  
  %
  %UIcontrol 13
  %
  counter = 19;
  NameString = 'UIcontrol 13';
  DetailsString = 'match background to figure 1';

  Fore = QmatNMR.ColorScheme.Button13Fore;
  ForeString = sprintf('[%0.4f %0.4f %0.4f]', Fore);

  Back = QmatNMR.ColorScheme.Button13Back;
  BackString = sprintf('[%0.4f %0.4f %0.4f]', Back);

  uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'string',NameString,...
			'units','Pixels',...
			'position',[10 windowheight-35-(counter*33) 100 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','text',...
			'string', DetailsString,...
			'units','Pixels',...
			'position',[110 windowheight-35-(counter*33) 200 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  mi((counter-1)*3+1) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', BackString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[330 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+2) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', ForeString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[501 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+3) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'units','Pixels',...
			'string', 'test test',...
			'position',[685 windowheight-35-(counter*33) 155 28],...
			'BackGroundColor', Back,...
			'ForeGroundColor', Fore);
  
  %
  %UIcontrol 14
  %
  counter = 20;
  NameString = 'UIcontrol 14';
  DetailsString = '';

  Fore = QmatNMR.ColorScheme.Button14Fore;
  ForeString = sprintf('[%0.4f %0.4f %0.4f]', Fore);

  Back = QmatNMR.ColorScheme.Button14Back;
  BackString = sprintf('[%0.4f %0.4f %0.4f]', Back);

  uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'string',NameString,...
			'units','Pixels',...
			'position',[10 windowheight-35-(counter*33) 100 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','text',...
			'string', DetailsString,...
			'units','Pixels',...
			'position',[110 windowheight-35-(counter*33) 200 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  mi((counter-1)*3+1) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', BackString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[330 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+2) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', ForeString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[501 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+3) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'units','Pixels',...
			'string', 'test test',...
			'position',[685 windowheight-35-(counter*33) 155 28],...
			'BackGroundColor', Back,...
			'ForeGroundColor', Fore);
  
  %
  %Text 1
  %
  counter = 21;
  NameString = 'Text 1';
  DetailsString = '';

  Fore = QmatNMR.ColorScheme.Text1Fore;
  ForeString = sprintf('[%0.4f %0.4f %0.4f]', Fore);

  Back = QmatNMR.ColorScheme.Text1Back;
  if isstr(Back)
    BackString = Back;
    Back = QmatNMR.ColorScheme.Figure1Back;
  else
    BackString = sprintf('[%0.4f %0.4f %0.4f]', Back);
  end
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'string',NameString,...
			'units','Pixels',...
			'position',[10 windowheight-35-(counter*33) 100 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','text',...
			'string', DetailsString,...
			'units','Pixels',...
			'position',[110 windowheight-35-(counter*33) 200 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  mi((counter-1)*3+1) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', BackString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[330 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+2) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', ForeString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[501 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+3) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'units','Pixels',...
			'string', 'test test',...
			'position',[685 windowheight-35-(counter*33) 155 28],...
			'BackGroundColor', Back,...
			'ForeGroundColor', Fore);
  
  %
  %Text 2
  %
  counter = 22;
  NameString = 'Text 2';
  DetailsString = '';

  Fore = QmatNMR.ColorScheme.Text2Fore;
  ForeString = sprintf('[%0.4f %0.4f %0.4f]', Fore);

  Back = QmatNMR.ColorScheme.Text2Back;
  if isstr(Back)
    BackString = Back;
    Back = QmatNMR.ColorScheme.Figure1Back;
  else
    BackString = sprintf('[%0.4f %0.4f %0.4f]', Back);
  end
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'string',NameString,...
			'units','Pixels',...
			'position',[10 windowheight-35-(counter*33) 100 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','text',...
			'string', DetailsString,...
			'units','Pixels',...
			'position',[110 windowheight-35-(counter*33) 200 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  mi((counter-1)*3+1) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', BackString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[330 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+2) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', ForeString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[501 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+3) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'units','Pixels',...
			'string', 'test test',...
			'position',[685 windowheight-35-(counter*33) 155 28],...
			'BackGroundColor', Back,...
			'ForeGroundColor', Fore);
  
  %
  %Text 3
  %
  counter = 23;
  NameString = 'Text 3';
  DetailsString = '';

  Fore = QmatNMR.ColorScheme.Text3Fore;
  ForeString = sprintf('[%0.4f %0.4f %0.4f]', Fore);

  Back = QmatNMR.ColorScheme.Text3Back;
  if isstr(Back)
    BackString = Back;
    Back = QmatNMR.ColorScheme.Figure1Back;
  else
    BackString = sprintf('[%0.4f %0.4f %0.4f]', Back);
  end
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'string',NameString,...
			'units','Pixels',...
			'position',[10 windowheight-35-(counter*33) 100 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','text',...
			'string', DetailsString,...
			'units','Pixels',...
			'position',[110 windowheight-35-(counter*33) 200 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  mi((counter-1)*3+1) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', BackString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[330 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+2) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', ForeString,...
			'callback', ['Qsetcolorscheme(3, ' num2str(counter) ')'], ...
			'position',[501 windowheight-35-(counter*33) 154 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  mi((counter-1)*3+3) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'units','Pixels',...
			'string', 'test test',...
			'position',[685 windowheight-35-(counter*33) 155 28],...
			'BackGroundColor', Back,...
			'ForeGroundColor', Fore);
  
  %
  %Line Main
  %
  counter = 24;
  NameString = 'Line (main)';
  DetailsString = 'MUST be linespec format for colours!';

  Fore = QmatNMR.ColorScheme.LineMain;
  ForeString = Fore;
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'string',NameString,...
			'units','Pixels',...
			'position',[10 windowheight-35-(counter*33) 100 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','text',...
			'string', DetailsString,...
			'units','Pixels',...
			'position',[110 windowheight-35-(counter*33) 200 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  mi((counter-1)*3+1) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', ForeString,...
			'position',[425 windowheight-35-(counter*33) 154 28],...
			'callback', 'Qsetcolorscheme(4)', ...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);
  
  %
  %Line Dual
  %
  counter = 25;
  NameString = 'Line (dual)';
  DetailsString = 'MUST be linespec format for colours!';

  Fore = QmatNMR.ColorScheme.LineDual;
  ForeString = Fore;
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','pushbutton',...
			'string',NameString,...
			'units','Pixels',...
			'position',[10 windowheight-35-(counter*33) 100 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  uicontrol('Parent',QmatNMR.leginp5,...
			'style','text',...
			'string', DetailsString,...
			'units','Pixels',...
			'position',[110 windowheight-35-(counter*33) 200 28],...
			'BackGroundColor', QmatNMR.ColorScheme.Button13Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button13Fore);
  mi((counter-1)*3+1) = uicontrol('Parent',QmatNMR.leginp5,...
			'style','edit',...
			'units','Pixels',...
			'string', ForeString,...
			'position',[425 windowheight-35-(counter*33) 154 28],...
			'callback', 'Qsetcolorscheme(5)', ...
			'BackGroundColor', QmatNMR.ColorScheme.Button2Back, ...
			'ForeGroundColor', QmatNMR.ColorScheme.Button2Fore);


%
%resize the window and normalize all children
%
  QmatNMR.ComputerScreenSize = get(0, 'screensize');
  if ((QmatNMR.ComputerScreenSize(3) < windowwidth) | (QmatNMR.ComputerScreenSize(4) < windowheight))
    QmatNMR.ChangeFrom = [1  1 windowwidth windowheight];
    QTEMP1 = QmatNMR.leginp5;	     %define the window handle
    CorrectWindow

  else
    set(QmatNMR.leginp5, 'units', 'normalized');
    QTEMP1 = get(QmatNMR.leginp5, 'position');
    set(QmatNMR.leginp5, 'position', [(1-QTEMP1(3))/2 (1-QTEMP1(4))/2 QTEMP1(3:4)]);
  end


%
% Now save all button QmatNMR.handles in the userdata
% 
  set(QmatNMR.leginp5, 'userdata', mi);
  figure(QmatNMR.leginp5);

elseif ((nargin < 1) & (QmatNMR.leginp5 > 0))			%Figure window already exists so pull to front and update all buttons
  figure(QmatNMR.leginp5)
	

elseif command==2
  QmatNMR.handles = get(QmatNMR.leginp5, 'userdata');
  QTEMP1= get(gco, 'value')-1;
  
  if (QTEMP1)	%define pre-selected schemes
    eval(['QmatNMR.ColorScheme = QmatNMR.DefaultColorScheme' num2str(QTEMP1) ';']);

    QmatNMR.LineColor = QmatNMR.ColorScheme.LineMain;
    QmatNMR.color = QmatNMR.ColorScheme.LineDual;

    %
    %set some default parameters in order for the axis labels and title to have the right colour.
    %
    set(0, ...
       'DefaultAxesXcolor', QmatNMR.ColorScheme.AxisFore, ...
       'DefaultAxesYcolor', QmatNMR.ColorScheme.AxisFore, ...
       'DefaultAxesZcolor', QmatNMR.ColorScheme.AxisFore, ...
       'DefaultTextColor', QmatNMR.ColorScheme.AxisFore);


    disp(' ');
    disp('The colour scheme has been changed. Unfortunately, matNMR must be ');
    disp('restarted in order to show the full effects of the changes.');
    disp(' ');

    %
    %update all buttons in the window
    %
    try
      delete(QmatNMR.leginp5);
    end
    QmatNMR.leginp5 = [];
    Qsetcolorscheme
  end
  
    
elseif command==3
  QmatNMR.handles = get(QmatNMR.leginp5, 'userdata');

  switch (command2)
    case 1 	%frame 1
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+1), 'string')))));
      QmatNMR.ColorScheme.Frame1 = str2num(a);
      set(QmatNMR.handles((command2-1)*3+3), 'backgroundcolor', QmatNMR.ColorScheme.Frame1);

    case 2 	%frame 2
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+1), 'string')))));
      QmatNMR.ColorScheme.Frame2 = str2num(a);
      set(QmatNMR.handles((command2-1)*3+3), 'backgroundcolor', QmatNMR.ColorScheme.Frame2);

    case 3 	%figure 1
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+1), 'string')))));
      QmatNMR.ColorScheme.Figure1Back = str2num(a);
      set(QmatNMR.handles((command2-1)*3+3), 'backgroundcolor', QmatNMR.ColorScheme.Figure1Back);
      set(QmatNMR.leginp5, 'color', QmatNMR.ColorScheme.Figure1Back);

    case 4 	%figure 2
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+1), 'string')))));
      QmatNMR.ColorScheme.Figure2Back = str2num(a);
      set(QmatNMR.handles((command2-1)*3+3), 'backgroundcolor', QmatNMR.ColorScheme.Figure2Back);

    case 5 	%UImenu
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+2), 'string')))));
      QmatNMR.ColorScheme.UImenuFore = str2num(a);
      set(QmatNMR.handles((command2-1)*3+3), 'foregroundcolor', QmatNMR.ColorScheme.UImenuFore);

    case 6 	%axes
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+1), 'string')))));
      if strcmp(a, 'none')
        QmatNMR.ColorScheme.AxisBack = a;
	QTEMP1 = QmatNMR.ColorScheme.Figure1Back;
      else
        QmatNMR.ColorScheme.AxisBack = str2num(a);
	QTEMP1 = QmatNMR.ColorScheme.AxisBack;
      end
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+2), 'string')))));
      QmatNMR.ColorScheme.AxisFore = str2num(a);
      set(QmatNMR.handles((command2-1)*3+3), 'backgroundcolor', QTEMP1, 'foregroundcolor', QmatNMR.ColorScheme.AxisFore);

    case 7 	%UIcontrol 1
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+1), 'string')))));
      QmatNMR.ColorScheme.Button1Back = str2num(a);
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+2), 'string')))));
      QmatNMR.ColorScheme.Button1Fore = str2num(a);
      set(QmatNMR.handles((command2-1)*3+3), 'backgroundcolor', QmatNMR.ColorScheme.Button1Back, 'foregroundcolor', QmatNMR.ColorScheme.Button1Fore);

    case 8 	%UIcontrol 2
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+1), 'string')))));
      QmatNMR.ColorScheme.Button2Back = str2num(a);
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+2), 'string')))));
      QmatNMR.ColorScheme.Button2Fore = str2num(a);
      set(QmatNMR.handles((command2-1)*3+3), 'backgroundcolor', QmatNMR.ColorScheme.Button2Back, 'foregroundcolor', QmatNMR.ColorScheme.Button2Fore);

    case 9 	%UIcontrol 3
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+1), 'string')))));
      QmatNMR.ColorScheme.Button3Back = str2num(a);
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+2), 'string')))));
      QmatNMR.ColorScheme.Button3Fore = str2num(a);
      set(QmatNMR.handles((command2-1)*3+3), 'backgroundcolor', QmatNMR.ColorScheme.Button3Back, 'foregroundcolor', QmatNMR.ColorScheme.Button3Fore);

    case 10 	%UIcontrol 4
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+1), 'string')))));
      QmatNMR.ColorScheme.Button4Back = str2num(a);
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+2), 'string')))));
      QmatNMR.ColorScheme.Button4Fore = str2num(a);
      set(QmatNMR.handles((command2-1)*3+3), 'backgroundcolor', QmatNMR.ColorScheme.Button4Back, 'foregroundcolor', QmatNMR.ColorScheme.Button4Fore);

    case 11 	%UIcontrol 5
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+1), 'string')))));
      QmatNMR.ColorScheme.Button5Back = str2num(a);
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+2), 'string')))));
      QmatNMR.ColorScheme.Button5Fore = str2num(a);
      set(QmatNMR.handles((command2-1)*3+3), 'backgroundcolor', QmatNMR.ColorScheme.Button5Back, 'foregroundcolor', QmatNMR.ColorScheme.Button5Fore);

    case 12 	%UIcontrol 6
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+1), 'string')))));
      QmatNMR.ColorScheme.Button6Back = str2num(a);
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+2), 'string')))));
      QmatNMR.ColorScheme.Button6Fore = str2num(a);
      set(QmatNMR.handles((command2-1)*3+3), 'backgroundcolor', QmatNMR.ColorScheme.Button6Back, 'foregroundcolor', QmatNMR.ColorScheme.Button6Fore);

    case 13 	%UIcontrol 7
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+1), 'string')))));
      QmatNMR.ColorScheme.Button7Back = str2num(a);
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+2), 'string')))));
      QmatNMR.ColorScheme.Button7Fore = str2num(a);
      set(QmatNMR.handles((command2-1)*3+3), 'backgroundcolor', QmatNMR.ColorScheme.Button7Back, 'foregroundcolor', QmatNMR.ColorScheme.Button7Fore);

    case 14 	%UIcontrol 8
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+1), 'string')))));
      QmatNMR.ColorScheme.Button8Back = str2num(a);
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+2), 'string')))));
      QmatNMR.ColorScheme.Button8Fore = str2num(a);
      set(QmatNMR.handles((command2-1)*3+3), 'backgroundcolor', QmatNMR.ColorScheme.Button8Back, 'foregroundcolor', QmatNMR.ColorScheme.Button8Fore);

    case 15 	%UIcontrol 9
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+1), 'string')))));
      QmatNMR.ColorScheme.Button9Back = str2num(a);
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+2), 'string')))));
      QmatNMR.ColorScheme.Button9Fore = str2num(a);
      set(QmatNMR.handles((command2-1)*3+3), 'backgroundcolor', QmatNMR.ColorScheme.Button9Back, 'foregroundcolor', QmatNMR.ColorScheme.Button9Fore);

    case 16 	%UIcontrol 10
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+1), 'string')))));
      QmatNMR.ColorScheme.Button10Back = str2num(a);
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+2), 'string')))));
      QmatNMR.ColorScheme.Button10Fore = str2num(a);
      set(QmatNMR.handles((command2-1)*3+3), 'backgroundcolor', QmatNMR.ColorScheme.Button10Back, 'foregroundcolor', QmatNMR.ColorScheme.Button10Fore);

    case 17 	%UIcontrol 11
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+1), 'string')))));
      QmatNMR.ColorScheme.Button11Back = str2num(a);
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+2), 'string')))));
      QmatNMR.ColorScheme.Button11Fore = str2num(a);
      set(QmatNMR.handles((command2-1)*3+3), 'backgroundcolor', QmatNMR.ColorScheme.Button11Back, 'foregroundcolor', QmatNMR.ColorScheme.Button11Fore);

    case 18 	%UIcontrol 12
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+1), 'string')))));
      QmatNMR.ColorScheme.Button12Back = str2num(a);
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+2), 'string')))));
      QmatNMR.ColorScheme.Button12Fore = str2num(a);
      set(QmatNMR.handles((command2-1)*3+3), 'backgroundcolor', QmatNMR.ColorScheme.Button12Back, 'foregroundcolor', QmatNMR.ColorScheme.Button12Fore);

    case 19 	%UIcontrol 13
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+1), 'string')))));
      QmatNMR.ColorScheme.Button13Back = str2num(a);
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+2), 'string')))));
      QmatNMR.ColorScheme.Button13Fore = str2num(a);
      set(QmatNMR.handles((command2-1)*3+3), 'backgroundcolor', QmatNMR.ColorScheme.Button13Back, 'foregroundcolor', QmatNMR.ColorScheme.Button13Fore);

    case 20 	%UIcontrol 14
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+1), 'string')))));
      QmatNMR.ColorScheme.Button14Back = str2num(a);
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+2), 'string')))));
      QmatNMR.ColorScheme.Button14Fore = str2num(a);
      set(QmatNMR.handles((command2-1)*3+3), 'backgroundcolor', QmatNMR.ColorScheme.Button14Back, 'foregroundcolor', QmatNMR.ColorScheme.Button14Fore);

    case 21 	%Text 1
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+1), 'string')))));
      if strcmp(a, 'none')
        QmatNMR.ColorScheme.Text1Back = a;
	QTEMP1 = QmatNMR.ColorScheme.Figure1Back;
      else
        QmatNMR.ColorScheme.Text1Back = str2num(a);
	QTEMP1 = QmatNMR.ColorScheme.Text1Back;
      end
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+2), 'string')))));
      QmatNMR.ColorScheme.Text1Fore = str2num(a);
      set(QmatNMR.handles((command2-1)*3+3), 'backgroundcolor', QTEMP1, 'foregroundcolor', QmatNMR.ColorScheme.Text1Fore);

    case 22 	%Text 2
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+1), 'string')))));
      if strcmp(a, 'none')
        QmatNMR.ColorScheme.Text2Back = a;
	QTEMP1 = QmatNMR.ColorScheme.Figure1Back;
      else
        QmatNMR.ColorScheme.Text2Back = str2num(a);
	QTEMP1 = QmatNMR.ColorScheme.Text2Back;
      end
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+2), 'string')))));
      QmatNMR.ColorScheme.Text2Fore = str2num(a);
      set(QmatNMR.handles((command2-1)*3+3), 'backgroundcolor', QTEMP1, 'foregroundcolor', QmatNMR.ColorScheme.Text2Fore);

    case 23 	%Text 3
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+1), 'string')))));
      if strcmp(a, 'none')
        QmatNMR.ColorScheme.Text3Back = a;
	QTEMP1 = QmatNMR.ColorScheme.Figure1Back;
      else
        QmatNMR.ColorScheme.Text3Back = str2num(a);
	QTEMP1 = QmatNMR.ColorScheme.Text3Back;
      end
      a = fliplr(deblank(fliplr(deblank(get(QmatNMR.handles((command2-1)*3+2), 'string')))));
      QmatNMR.ColorScheme.Text3Fore = str2num(a);
      set(QmatNMR.handles((command2-1)*3+3), 'backgroundcolor', QTEMP1, 'foregroundcolor', QmatNMR.ColorScheme.Text3Fore);

    otherwise
      disp('Qsetcolorscheme ERROR: code not recognized. Aborting ...');
  end

  %
  %set some default parameters in order for the axis labels and title to have the right colour.
  %
  set(0, ...
       'DefaultAxesXcolor', QmatNMR.ColorScheme.AxisFore, ...
       'DefaultAxesYcolor', QmatNMR.ColorScheme.AxisFore, ...
       'DefaultAxesZcolor', QmatNMR.ColorScheme.AxisFore, ...
       'DefaultTextColor', QmatNMR.ColorScheme.AxisFore);


  %
  %make the window smaller when it's too big for the window
  %
  if ((QmatNMR.ComputerScreenSize(3) < 800) | (QmatNMR.ComputerScreenSize(4) < 900))
    QmatNMR.ChangeFrom = [1  1 windowwidth windowheight];
    QTEMP1 = QmatNMR.leginp5;	     %define the window handle
    CorrectWindow
  end  


elseif command==4	%line main
  watch;
  QmatNMR.handles = get(QmatNMR.leginp5, 'userdata');
  counter = 24;
  QmatNMR.LineColor = get(QmatNMR.handles((counter-1)*3+1), 'string');
  QmatNMR.ColorScheme.LineMain = QmatNMR.LineColor;


elseif command==5	%line dual
  watch;
  QmatNMR.handles = get(QmatNMR.leginp5, 'userdata');
  counter = 25;
  QmatNMR.color = get(QmatNMR.handles((counter-1)*3+1), 'string');
  QmatNMR.ColorScheme.LineDual = QmatNMR.color;


elseif command==6	%save colour scheme in options file
  disp(' ');
  disp('matNMR NOTICE: The colour scheme has been changed. Unfortunately, matNMR must be ');
  disp('matNMR NOTICE: restarted in order to show the full effects of the changes.');
  disp(' ');

  SetOptions(2)
  saveoptions
end
