%
%
%
% matNMR v. 3.9.94 - A processing toolbox for NMR/EPR under MATLAB
%
% Copyright (c) 1997-2009  Jacco van Beek
% jabe@users.sourceforge.net
%
%
% This program is free software; you can redistribute it and/or
% modify it under the terms of the GNU General Public License
% as published by the Free Software Foundation; either version 2
% of the License, or (at your option) any later version.
% 
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with this program; if not, write to the Free Software
% Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
%
% --> gpl.txt
%
% Should yo be too lazy to do this, please remember:
%    - The code may be altered under the condition that all changes are clearly marked 
%      with your name and the date and that none of the names currently present in the 
%      code are removed.
%
% Furthermore:
%    -Please update the BugFixes.txt (i.e. the changelog file)!
%    -Please inform me of useful changes and annoying bugs!
%
% Jacco
%
%
% ====================================================================================
%
%
%settings.m changes some default parameters such that matNMR looks nice
%
%01-08-'97

try
  %
  %First determine what the current values are for the parameters that are going to be changed such that they
  %can be restored when quitting matNMR.
  %
  QTEMP1 = get(0, 'DefaultFigureColor');
  if isstr(QTEMP1)
    QTEMP1 = ['''' QTEMP1 ''''];
  else
    QTEMP1 = ['[' num2str(QTEMP1(1), 10) ' ' num2str(QTEMP1(2), 10) ' ' num2str(QTEMP1(3), 10) ']'];
  end
  QTEMP2 = get(0, 'DefaultUIControlbackgroundcolor');
  if isstr(QTEMP2)
    QTEMP2 = ['''' QTEMP2 ''''];
  else
    QTEMP2 = ['[' num2str(QTEMP2(1), 10) ' ' num2str(QTEMP2(2), 10) ' ' num2str(QTEMP2(3), 10) ']'];
  end
  QTEMP3 = get(0, 'DefaultUIControlForeGroundColor');
  if isstr(QTEMP3)
    QTEMP3 = ['''' QTEMP3 ''''];
  else
    QTEMP3 = ['[' num2str(QTEMP3(1), 10) ' ' num2str(QTEMP3(2), 10) ' ' num2str(QTEMP3(3), 10) ']'];
  end
  QTEMP4 = get(0, 'DefaultAxesColor');
  if isstr(QTEMP4)
    QTEMP4 = ['''' QTEMP4 ''''];
  else
    QTEMP4 = ['[' num2str(QTEMP4(1), 10) ' ' num2str(QTEMP4(2), 10) ' ' num2str(QTEMP4(3), 10) ']'];
  end
  QTEMP5 = get(0, 'DefaultAxesXcolor');
  if isstr(QTEMP5)
    QTEMP5 = ['''' QTEMP5 ''''];
  else
    QTEMP5 = ['[' num2str(QTEMP5(1), 10) ' ' num2str(QTEMP5(2), 10) ' ' num2str(QTEMP5(3), 10) ']'];
  end
  QTEMP6 = get(0, 'DefaultAxesYcolor');
  if isstr(QTEMP6)
    QTEMP6 = ['''' QTEMP6 ''''];
  else
    QTEMP6 = ['[' num2str(QTEMP6(1), 10) ' ' num2str(QTEMP6(2), 10) ' ' num2str(QTEMP6(3), 10) ']'];
  end
  QTEMP7 = get(0, 'DefaultAxesZcolor');
  if isstr(QTEMP7)
    QTEMP7 = ['''' QTEMP7 ''''];
  else
    QTEMP7 = ['[' num2str(QTEMP7(1), 10) ' ' num2str(QTEMP7(2), 10) ' ' num2str(QTEMP7(3), 10) ']'];
  end
  QTEMP8 = get(0, 'DefaultLineColor');
  if isstr(QTEMP8)
    QTEMP8 = ['''' QTEMP8 ''''];
  else
    QTEMP8 = ['[' num2str(QTEMP8(1), 10) ' ' num2str(QTEMP8(2), 10) ' ' num2str(QTEMP8(3), 10) ']'];
  end
  QTEMP9 = get(0, 'DefaultTextColor');
  if isstr(QTEMP9)
    QTEMP9 = ['''' QTEMP9 ''''];
  else
    QTEMP9 = ['[' num2str(QTEMP9(1), 10) ' ' num2str(QTEMP9(2), 10) ' ' num2str(QTEMP9(3), 10) ']'];
  end
  
  QmatNMR.WarningSettings = warning;	%read out the current warning settings
  
  %%%QmatNMR.RestoreUserDefaultValues = ['set(0, ''DefaultFigureMenubar'', ''' get(0, 'DefaultFigureMenubar') ''',' ...
  %%%				'''DefaultFigureNextPlot'', ''' get(0, 'DefaultFigureNextPlot') ''',' ...
  %%%				'''DefaultFigureColor'', '  QTEMP1 ',' ...
  %%%				'''DefaultFigureNumberTitle'', ''' get(0, 'DefaultFigureNumberTitle') ''',' ...
  %%%				'''DefaultFigurePaperType'', ''' get(0, 'DefaultFigurePaperType') ''',' ...
  %%%				'''DefaultUIControlbackgroundcolor'', ' QTEMP2 ',' ...
  %%%				'''DefaultUIControlFontUnits'', ''' get(0, 'DefaultUIControlFontUnits') ''',' ...
  %%%				'''DefaultUIControlFontSize'', ' num2str(get(0, 'DefaultUIControlFontSize')) ',' ...
  %%%				'''DefaultUIControlFontAngle'', ''' get(0, 'DefaultUIControlFontAngle') ''',' ...
  %%%				'''DefaultUIControlFontName'', ''' get(0, 'DefaultUIControlFontName') ''',' ...
  %%%				'''DefaultUIControlInterruptible'', ''' get(0, 'DefaultUIControlInterruptible') ''',' ...
  %%%				'''DefaultUIControlForeGroundColor'', ' QTEMP3 ',' ...
  %%%				'''DefaultUIControlHorizontalAlignment'', ''' get(0, 'DefaultUIControlHorizontalAlignment') ''',' ...
  %%%				'''DefaultUIControlSelectionHighLight'', ''' get(0, 'DefaultUIControlSelectionHighLight') ''',' ...
  %%%				'''DefaultUIMenuSelectionHighLight'', ''' get(0, 'DefaultUIMenuSelectionHighLight') ''',' ...
  %%%				'''DefaultAxesColor'', ' QTEMP4 ',' ...
  %%%				'''DefaultAxesDrawmode'', ''' get(0, 'DefaultAxesDrawmode') ''',' ...
  %%%				'''DefaultAxesFontUnits'', ''' get(0, 'DefaultAxesFontUnits') ''',' ...
  %%%				'''DefaultAxesFontSize'', ' num2str(get(0, 'DefaultAxesFontSize')) ',' ...
  %%%				'''DefaultAxesFontAngle'', ''' get(0, 'DefaultAxesFontAngle') ''',' ...
  %%%				'''DefaultAxesFontName'', ''' get(0, 'DefaultAxesFontName') ''',' ...
  %%%				'''DefaultAxesGridLineStyle'', ''' get(0, 'DefaultAxesGridLineStyle') ''',' ...
  %%%				'''DefaultAxesInterruptible'', ''' get(0, 'DefaultAxesInterruptible') ''',' ...
  %%%				'''DefaultAxesLayer'', ''' get(0, 'DefaultAxesLayer') ''',' ...
  %%%				'''DefaultAxesNextPlot'', ''' get(0, 'DefaultAxesNextPlot') ''',' ...
  %%%				'''DefaultAxesUnits'', ''' get(0, 'DefaultAxesUnits') ''',' ...
  %%%				'''DefaultAxesXcolor'', ' QTEMP5 ',' ...
  %%%				'''DefaultAxesYcolor'', ' QTEMP6 ',' ...
  %%%				'''DefaultAxesZcolor'', ' QTEMP7 ',' ...
  %%%				'''DefaultAxesVisible'', ''' get(0, 'DefaultAxesVisible') ''',' ...
  %%%				'''DefaultLineColor'', ' QTEMP8 ',' ...
  %%%				'''DefaultLineLineStyle'', ''' get(0, 'DefaultLineLineStyle') ''',' ...
  %%%				'''DefaultLineLineWidth'', ' num2str(get(0, 'DefaultLineLineWidth')) ',' ...
  %%%				'''DefaultLineMarker'', ''' get(0, 'DefaultLineMarker') ''',' ...
  %%%				'''DefaultLineMarkerSize'', ' num2str(get(0, 'DefaultLineMarkerSize')) ',' ...
  %%%				'''DefaultLineHittest'', ''' get(0, 'DefaultLineHittest') ''',' ...
  %%%				'''DefaultPatchHittest'', ''' get(0, 'DefaultPatchHittest') ''',' ...
  %%%				'''DefaultSurfaceHittest'', ''' get(0, 'DefaultSurfaceHittest') ''',' ...
  %%%				'''DefaultTextHittest'', ''' get(0, 'DefaultTextHittest') ''',' ...
  %%%				'''DefaultTextColor'', ' QTEMP9 ',' ...
  %%%				'''DefaultTextFontUnits'', ''' get(0, 'DefaultTextFontUnits') ''',' ...
  %%%				'''DefaultTextFontSize'', ' num2str(get(0, 'DefaultTextFontSize')) ',' ...
  %%%				'''DefaultTextFontName'', ''' get(0, 'DefaultTextFontName') ''',' ...
  %%%				'''DefaultTextVerticalAlignment'', ''' get(0, 'DefaultTextVerticalAlignment') ''',' ...
  %%%				'''DefaultTextHorizontalAlignment'', ''' get(0, 'DefaultTextHorizontalAlignment') '''' ...
  %%%				'); warning(QmatNMR.WarningSettings);'];
  %%%
  %%%%
  %%%%Now set the matNMR defaults
  %%%%
  %%%set(0, 'DefaultFigureMenubar', 'none', ...
  %%%       'DefaultFigureNextPlot', 'add', ...
  %%%       'DefaultFigureColor', 'black', ...
  %%%       'DefaultFigureNumberTitle', 'off', ...
  %%%       'DefaultFigurePaperType', 'a4letter', ...
  %%%       'DefaultUIControlbackgroundcolor', [0.702 0.702 .702], ...
  %%%       'DefaultUIControlFontUnits', 'points', ...
  %%%       'DefaultUIControlFontSize', QmatNMRsettings.DefaultUIFontSize, ...
  %%%       'DefaultUIControlFontAngle', 'normal', ...
  %%%       'DefaultUIControlFontName', 'Helvetica', ...       
  %%%       'DefaultUIControlInterruptible', 'off', ...
  %%%       'DefaultUIControlForeGroundColor', 'black', ...
  %%%       'DefaultUIControlHorizontalAlignment', 'center', ...
  %%%       'DefaultUIControlSelectionHighLight', 'on', ...
  %%%       'DefaultUIMenuSelectionHighLight', 'on', ...
  %%%       'DefaultAxesColor', 'none', ...
  %%%       'DefaultAxesDrawmode', 'fast', ...
  %%%       'DefaultAxesFontUnits', 'points', ...
  %%%       'DefaultAxesFontSize', 12, ...
  %%%       'DefaultAxesFontAngle', 'normal', ...
  %%%       'DefaultAxesFontName', 'Helvetica', ...       
  %%%       'DefaultAxesGridLineStyle', ':', ...
  %%%       'DefaultAxesInterruptible', 'on', ...
  %%%       'DefaultAxesLayer', 'Top', ...
  %%%       'DefaultAxesNextPlot', 'replace', ...
  %%%       'DefaultAxesUnits', 'normalized', ...
  %%%       'DefaultAxesXcolor', [1 1 1], ...
  %%%       'DefaultAxesYcolor', [1 1 1], ...
  %%%       'DefaultAxesZcolor', [1 1 1], ...
  %%%       'DefaultAxesVisible', 'on', ...
  %%%       'DefaultLineColor', 'yellow', ...
  %%%       'DefaultLineLineStyle', '-', ...
  %%%       'DefaultLineLineWidth', 0.5, ...
  %%%       'DefaultLineMarker', 'none', ...
  %%%       'DefaultLineMarkerSize', 6, ...
  %%%       'DefaultLineHittest', 'off', ...
  %%%       'DefaultPatchHittest', 'off', ...
  %%%       'DefaultSurfaceHittest', 'off', ...
  %%%       'DefaultTextHittest', 'off', ...
  %%%       'DefaultTextColor', [1 1 1], ...
  %%%       'DefaultTextFontUnits', 'Points', ...
  %%%       'DefaultTextFontSize', 12, ...
  %%%       'DefaultTextFontName', 'Helvetica', ...
  %%%       'DefaultTextVerticalAlignment', 'middle', ...
  %%%       'DefaultTextHorizontalAlignment', 'left');
  
  
  QmatNMR.RestoreUserDefaultValues = ['set(0, ''DefaultFigureMenubar'', ''' get(0, 'DefaultFigureMenubar') ''',' ...
  				'''DefaultFigureNextPlot'', ''' get(0, 'DefaultFigureNextPlot') ''',' ...
  				'''DefaultFigureColor'', '  QTEMP1 ',' ...
  				'''DefaultFigureNumberTitle'', ''' get(0, 'DefaultFigureNumberTitle') ''',' ...
  				'''DefaultFigurePaperType'', ''' get(0, 'DefaultFigurePaperType') ''',' ...
  				'''DefaultUIControlbackgroundcolor'', ' QTEMP2 ',' ...
  				'''DefaultUIControlFontUnits'', ''' get(0, 'DefaultUIControlFontUnits') ''',' ...
  				'''DefaultUIControlFontSize'', ' num2str(get(0, 'DefaultUIControlFontSize')) ',' ...
  				'''DefaultUIControlFontAngle'', ''' get(0, 'DefaultUIControlFontAngle') ''',' ...
  				'''DefaultUIControlFontName'', ''' get(0, 'DefaultUIControlFontName') ''',' ...
  				'''DefaultUIControlInterruptible'', ''' get(0, 'DefaultUIControlInterruptible') ''',' ...
  				'''DefaultUIControlForeGroundColor'', ' QTEMP3 ',' ...
  				'''DefaultUIControlHorizontalAlignment'', ''' get(0, 'DefaultUIControlHorizontalAlignment') ''',' ...
  				'''DefaultUIControlSelectionHighLight'', ''' get(0, 'DefaultUIControlSelectionHighLight') ''',' ...
  				'''DefaultUIMenuSelectionHighLight'', ''' get(0, 'DefaultUIMenuSelectionHighLight') ''',' ...
  				'''DefaultAxesColor'', ' QTEMP4 ',' ...
  				'''DefaultAxesDrawmode'', ''' get(0, 'DefaultAxesDrawmode') ''',' ...
  				'''DefaultAxesFontUnits'', ''' get(0, 'DefaultAxesFontUnits') ''',' ...
  				'''DefaultAxesFontSize'', ' num2str(get(0, 'DefaultAxesFontSize')) ',' ...
  				'''DefaultAxesFontAngle'', ''' get(0, 'DefaultAxesFontAngle') ''',' ...
  				'''DefaultAxesFontName'', ''' get(0, 'DefaultAxesFontName') ''',' ...
  				'''DefaultAxesGridLineStyle'', ''' get(0, 'DefaultAxesGridLineStyle') ''',' ...
  				'''DefaultAxesInterruptible'', ''' get(0, 'DefaultAxesInterruptible') ''',' ...
  				'''DefaultAxesLayer'', ''' get(0, 'DefaultAxesLayer') ''',' ...
  				'''DefaultAxesNextPlot'', ''' get(0, 'DefaultAxesNextPlot') ''',' ...
  				'''DefaultAxesUnits'', ''' get(0, 'DefaultAxesUnits') ''',' ...
  				'''DefaultAxesXcolor'', ' QTEMP5 ',' ...
  				'''DefaultAxesYcolor'', ' QTEMP6 ',' ...
  				'''DefaultAxesZcolor'', ' QTEMP7 ',' ...
  				'''DefaultAxesVisible'', ''' get(0, 'DefaultAxesVisible') ''',' ...
  				'''DefaultLineColor'', ' QTEMP8 ',' ...
  				'''DefaultLineLineStyle'', ''' get(0, 'DefaultLineLineStyle') ''',' ...
  				'''DefaultLineLineWidth'', ' num2str(get(0, 'DefaultLineLineWidth')) ',' ...
  				'''DefaultLineMarker'', ''' get(0, 'DefaultLineMarker') ''',' ...
  				'''DefaultLineMarkerSize'', ' num2str(get(0, 'DefaultLineMarkerSize')) ',' ...
  				'''DefaultLineHittest'', ''' get(0, 'DefaultLineHittest') ''',' ...
  				'''DefaultPatchHittest'', ''' get(0, 'DefaultPatchHittest') ''',' ...
  				'''DefaultSurfaceHittest'', ''' get(0, 'DefaultSurfaceHittest') ''',' ...
  				'''DefaultTextHittest'', ''' get(0, 'DefaultTextHittest') ''',' ...
  				'''DefaultTextColor'', ' QTEMP9 ',' ...
  				'''DefaultTextFontUnits'', ''' get(0, 'DefaultTextFontUnits') ''',' ...
  				'''DefaultTextFontSize'', ' num2str(get(0, 'DefaultTextFontSize')) ',' ...
  				'''DefaultTextFontName'', ''' get(0, 'DefaultTextFontName') ''',' ...
  				'''DefaultTextVerticalAlignment'', ''' get(0, 'DefaultTextVerticalAlignment') ''',' ...
  				'''DefaultTextHorizontalAlignment'', ''' get(0, 'DefaultTextHorizontalAlignment') '''' ...
  				'); warning(QmatNMR.WarningSettings);'];
  
  %
  %Now set the matNMR defaults
  %                                                                             
  set(0, 'DefaultFigureNextPlot', 'add', ...                                    
         'DefaultFigurePaperType', 'a4letter', ...                              
         'DefaultUIControlFontUnits', 'points', ...                             
         'DefaultUIControlFontSize', QmatNMRsettings.DefaultUIFontSize, ...     
         'DefaultUIControlFontAngle', 'normal', ...                             
         'DefaultUIControlFontName', 'Helvetica', ...                           
         'DefaultUIControlInterruptible', 'off', ...                            
         'DefaultUIControlHorizontalAlignment', 'center', ...                   
         'DefaultUIControlSelectionHighLight', 'on', ...                        
         'DefaultUIMenuSelectionHighLight', 'on', ...                           
         'DefaultAxesDrawmode', 'fast', ...                                     
         'DefaultAxesFontUnits', 'points', ...                                  
         'DefaultAxesFontSize', 12, ...                                         
         'DefaultAxesFontAngle', 'normal', ...                                  
         'DefaultAxesFontName', 'Helvetica', ...                                
         'DefaultAxesGridLineStyle', ':', ...                                   
         'DefaultAxesInterruptible', 'on', ...                                  
         'DefaultAxesLayer', 'Top', ...                                         
         'DefaultAxesNextPlot', 'replace', ...                                  
         'DefaultAxesUnits', 'normalized', ...                                  
         'DefaultAxesVisible', 'on', ...                                        
         'DefaultLineLineStyle', '-', ...
         'DefaultLineLineWidth', 0.5, ...       
         'DefaultLineMarker', 'none', ...                                       
         'DefaultLineMarkerSize', 6, ...                                        
         'DefaultPatchHittest', 'off', ...                                      
         'DefaultSurfaceHittest', 'off', ...                                    
         'DefaultTextHittest', 'off', ...                                       
         'DefaultTextFontUnits', 'Points', ...                                  
         'DefaultTextFontSize', 12, ...                                         
         'DefaultTextFontName', 'Helvetica', ...                                
         'DefaultTextVerticalAlignment', 'middle', ...                          
         'DefaultTextHorizontalAlignment', 'left');                             
  warning off;                                                                  
                                                                                
  clear QTEMP*                                                                  
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                

catch
%
%call the generic error handler routine if anything goes wrong
%
  errorhandler
end
