%
%
%
% matNMR v. 3.9.94 - A processing toolbox for NMR/EPR under MATLAB
%
% Copyright (c) 1997-2009  Jacco van Beek
% jabe@users.sourceforge.net
%
%
% This program is free software; you can redistribute it and/or
% modify it under the terms of the GNU General Public License
% as published by the Free Software Foundation; either version 2
% of the License, or (at your option) any later version.
% 
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with this program; if not, write to the Free Software
% Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
%
% --> gpl.txt
%
% Should yo be too lazy to do this, please remember:
%    - The code may be altered under the condition that all changes are clearly marked 
%      with your name and the date and that none of the names currently present in the 
%      code are removed.
%
% Furthermore:
%    -Please update the BugFixes.txt (i.e. the changelog file)!
%    -Please inform me of useful changes and annoying bugs!
%
% Jacco
%
%
% ====================================================================================
%
%
function T1pk_init

% Initialize all the GUI controls for T1fit
% 5-3-94 SMB (Bren@SLAC.stanford.edu)

%
% adapted for matNMR by Jacco van Beek
% 1-1-'97
%

global QmatNMR

        QmatNMR.ScreenSize = get(0, 'screensize');
	QTEMP = [];
	QTEMP.SubPlots = 1;
	T1Fig = figure('numbertitle','off',...
	       'Name','T1 Fitting Routine for matNMR',...
	       'units', 'pixels', ...
	       'position',[((QmatNMR.ScreenSize(3)-800)/2) ((QmatNMR.ScreenSize(4)-600)/2) 800 600],...
	       'backingstore', 'on', ...
	       'paperorientation', 'landscape', ...
               'papertype', 'a4letter', ....
	       'paperunits', 'normalized', ...
	       'paperposition', [0.1 0.1 .8 .8], ...
	       'CloseRequestFCN', 'stopT1fit', ...
               'menubar', 'none', ...
	       'userdata', QTEMP, ...
	       'color', QmatNMR.ColorScheme.Figure1Back, ...
	       'Tag', 'T1fit');
        if (QmatNMR.unittype == 1)
          set(T1Fig, 'resize', 'on');
        else
          set(T1Fig, 'resize', 'off');
        end

  %
  %To work around a Matlab bug (see BugFixes.txt, 11-05-'04) we redefine the position and units.
  %
  set(T1Fig, 'units', 'pixels', 'position', [((QmatNMR.ScreenSize(3)-800)/2) ((QmatNMR.ScreenSize(4)-600)/2) 800 600]);

	set(gca, 'visible', 'off');

	%  Uimenubar Object Creation 

	QmatNMR.Q1 = uimenu(T1Fig, 'label', '   Load parameters   ', 'Position', [1]);
		uimenu(QmatNMR.Q1, 'label', 'Load parameters', 'callback', 'T1fit(''loadpars1'');');

	QmatNMR.Q2 = uimenu(T1Fig, 'label', '   View Fit Results   ', 'Position', [2]);
		uimenu(QmatNMR.Q2, 'label', 'Define Results Variable', 'callback', 'T1fit(''defvar1'');');
		uimenu(QmatNMR.Q2, 'label', 'View Fit Results', 'callback', 'T1fit(''view1'');');
		uimenu(QmatNMR.Q2, 'label', 'Add Fit Results to plot', 'callback', 'ZoomMatNMR FitWindow; T1fit(''viewadd1'');');
		uimenu(QmatNMR.Q2, 'label', 'Toggle Zoom status', 'callback', 'ZoomMatNMR FitWindow');

  	QmatNMR.Q3 = uimenu(T1Fig, 'label', '   Plot Manipulations   ', 'position', [3]);
		uimenu(QmatNMR.Q3, 'label', 'Legend', 'callback', 'QezLegend', 'separator', 'on');
		QmatNMR.Q3Axis = uimenu(QmatNMR.Q3, 'label', 'Axis properties');
			uimenu(QmatNMR.Q3Axis, 'label', 'Axis On/Off/Etc', 'callback', 'askaxis');
			uimenu(QmatNMR.Q3Axis, 'label', 'Clear Axis', 'callback', 'askclearaxis');	
			uimenu(QmatNMR.Q3Axis, 'label', 'Axis Colors', 'callback', 'askaxiscolors');	
			uimenu(QmatNMR.Q3Axis, 'label', 'Axis Directions', 'callback', 'askdirs');	
			uimenu(QmatNMR.Q3Axis, 'label', 'Axis Labels', 'callback', 'askaxislabels');	
			uimenu(QmatNMR.Q3Axis, 'label', 'Axis Locations', 'callback', 'askaxislocation');	
			uimenu(QmatNMR.Q3Axis, 'label', 'Axis Position', 'callback', 'askaxisposition');
			uimenu(QmatNMR.Q3Axis, 'label', 'Axis View', 'callback', 'findcurrentfigure; askaxisview');
			uimenu(QmatNMR.Q3Axis, 'label', 'Title', 'callback', 'asktitle');
		uimenu(QmatNMR.Q3, 'label', 'Box', 'callback', 'askbox');
		uimenu(QmatNMR.Q3, 'label', 'Font Properties', 'callback', 'askfont');
		uimenu(QmatNMR.Q3, 'label', 'Grid', 'callback', 'askgrid');
		uimenu(QmatNMR.Q3, 'label', 'Hold', 'callback', 'askhold');
		QmatNMR.Q3Line = uimenu(QmatNMR.Q3, 'label', 'Line properties');
			QTEMP1= uimenu(QmatNMR.Q3Line, 'label', 'LineStyle');
				uimenu(QTEMP1,'label', '-', 'callback', 'Linestyle(''-''); disp(''Linestyle set to solid'');');
				uimenu(QTEMP1,'label', '--', 'callback', 'Linestyle(''--''); disp(''Linestyle set to dashed'');');
				uimenu(QTEMP1,'label', ':', 'callback', 'Linestyle('':''); disp(''Linestyle set to dotted'');');
				uimenu(QTEMP1,'label', '-.', 'callback', 'Linestyle(''-.''); disp(''Linestyle set to dash-dot'');');
				uimenu(QTEMP1,'label', 'None', 'callback', 'Linestyle(''none''); disp(''Linestyle set to none'');');
			QTEMP1 = uimenu(QmatNMR.Q3Line, 'label', 'LineWidth');
				uimenu(QTEMP1, 'label', '0.05', 'callback', 'Linewidth(0.05); disp(''Linewidth set to 0.05'');');	
				uimenu(QTEMP1, 'label', '0.10', 'callback', 'Linewidth(0.1); disp(''Linewidth set to 0.10'');');	
				uimenu(QTEMP1, 'label', '0.15', 'callback', 'Linewidth(0.15); disp(''Linewidth set to 0.15'');');	
				uimenu(QTEMP1, 'label', '0.25', 'callback', 'Linewidth(0.25); disp(''Linewidth set to 0.25'');');	
				uimenu(QTEMP1, 'label', '0.5', 'callback', 'Linewidth(0.5); disp(''Linewidth set to 0.5'');');	
				uimenu(QTEMP1, 'label', '1.0', 'callback', 'Linewidth(1.0); disp(''Linewidth set to 1.0'');');	
				uimenu(QTEMP1, 'label', '1.5', 'callback', 'Linewidth(1.5); disp(''Linewidth set to 1.5'');');	
				uimenu(QTEMP1, 'label', '2.0', 'callback', 'Linewidth(2.0); disp(''Linewidth set to 2.0'');');	
				uimenu(QTEMP1, 'label', '3.0', 'callback', 'Linewidth(3.0); disp(''Linewidth set to 3.0'');');	
				uimenu(QTEMP1, 'label', '4.0', 'callback', 'Linewidth(4.0); disp(''Linewidth set to 4.0'');');	
				uimenu(QTEMP1, 'label', '5.0', 'callback', 'Linewidth(5.0); disp(''Linewidth set to 5.0'');');	
				uimenu(QTEMP1, 'label', '6.0', 'callback', 'Linewidth(6.0); disp(''Linewidth set to 6.0'');');	
				uimenu(QTEMP1, 'label', '7.0', 'callback', 'Linewidth(7.0); disp(''Linewidth set to 7.0'');');	
				uimenu(QTEMP1, 'label', '8.0', 'callback', 'Linewidth(8.0); disp(''Linewidth set to 8.0'');');	
				uimenu(QTEMP1, 'label', '9.0', 'callback', 'Linewidth(9.0); disp(''Linewidth set to 9.0'');');	
				uimenu(QTEMP1, 'label', '10.0', 'callback', 'Linewidth(10.0); disp(''Linewidth set to 10.0'');');	
			QTEMP1= uimenu(QmatNMR.Q3Line, 'label', 'Marker');
				uimenu(QTEMP1,'label', 'None', 'callback', 'Marker(''none''); disp(''Marker set to none'');');
				uimenu(QTEMP1,'label', 'Point', 'callback', 'Marker(''.''); disp(''Marker set to point'');');
				uimenu(QTEMP1,'label', 'Plus', 'callback', 'Marker(''+''); disp(''Marker set to plus'');');
				uimenu(QTEMP1,'label', 'Circle', 'callback', 'Marker(''o''); disp(''Marker set to circle'');');
				uimenu(QTEMP1,'label', 'Asterisk', 'callback', 'Marker(''*''); disp(''Marker set to asterisk'');');
				uimenu(QTEMP1,'label', 'Cross', 'callback', 'Marker(''x''); disp(''Marker set to cross'');');
				uimenu(QTEMP1,'label', 'Square', 'callback', 'Marker(''s''); disp(''Marker set to square'');');
				uimenu(QTEMP1,'label', 'Diamond', 'callback', 'Marker(''d''); disp(''Marker set to triangle diamond'');');
				uimenu(QTEMP1,'label', 'Triangle up', 'callback', 'Marker(''^''); disp(''Marker set to triangle up'');');
				uimenu(QTEMP1,'label', 'Triangle down', 'callback', 'Marker(''v''); disp(''Marker set to triangle down'');');
				uimenu(QTEMP1,'label', 'Triangle right', 'callback', 'Marker(''>''); disp(''Marker set to triangle right'');');
				uimenu(QTEMP1,'label', 'Triangle left', 'callback', 'Marker(''<''); disp(''Marker set to triangle left'');');
				uimenu(QTEMP1,'label', 'Pentagram', 'callback', 'Marker(''p''); disp(''Marker set to pentagram'');');
				uimenu(QTEMP1,'label', 'Hexagram', 'callback', 'Marker(''h''); disp(''Marker set to hexagram'');');
			QTEMP1= uimenu(QmatNMR.Q3Line, 'label', 'Marker Size');
				uimenu(QTEMP1, 'label', '0.5', 'callback', 'Markersize(0.5); disp(''Marker Size set to 0.5'');');	
				uimenu(QTEMP1, 'label', '1.0', 'callback', 'Markersize(1.0); disp(''Marker Size set to 1.0'');');	
				uimenu(QTEMP1, 'label', '1.5', 'callback', 'Markersize(1.5); disp(''Marker Size set to 1.5'');');	
				uimenu(QTEMP1, 'label', '2.0', 'callback', 'Markersize(2.0); disp(''Marker Size set to 2.0'');');	
				uimenu(QTEMP1, 'label', '3.0', 'callback', 'Markersize(3.0); disp(''Marker Size set to 3.0'');');	
				uimenu(QTEMP1, 'label', '4.0', 'callback', 'Markersize(4.0); disp(''Marker Size set to 4.0'');');	
				uimenu(QTEMP1, 'label', '5.0', 'callback', 'Markersize(5.0); disp(''Marker Size set to 5.0'');');	
				uimenu(QTEMP1, 'label', '6.0', 'callback', 'Markersize(6.0); disp(''Marker Size set to 6.0'');');	
				uimenu(QTEMP1, 'label', '7.0', 'callback', 'Markersize(7.0); disp(''Marker Size set to 7.0'');');	
				uimenu(QTEMP1, 'label', '8.0', 'callback', 'Markersize(8.0); disp(''Marker Size set to 8.0'');');	
				uimenu(QTEMP1, 'label', '9.0', 'callback', 'Markersize(9.0); disp(''Marker Size set to 9.0'');');	
				uimenu(QTEMP1, 'label', '10.0', 'callback', 'Markersize(10.0); disp(''Marker Size set to 10.0'');');	
		uimenu(QmatNMR.Q3, 'label', 'Scaling Limits', 'callback', 'asklims');
		uimenu(QmatNMR.Q3, 'label', 'Scaling Types', 'callback', 'askscales');
		uimenu(QmatNMR.Q3, 'label', 'Shading', 'callback', 'askshading');
		QmatNMR.Q3Tick = uimenu(QmatNMR.Q3, 'label', 'Tick properties');
			uimenu(QmatNMR.Q3Tick, 'label', 'Tick direction', 'callback', 'asktickdir');
			uimenu(QmatNMR.Q3Tick, 'label', 'Tick Labels', 'callback', 'askticklabel');	
			uimenu(QmatNMR.Q3Tick, 'label', 'Tick Lengths', 'callback', 'askticklengths');	
			uimenu(QmatNMR.Q3Tick, 'label', 'Tick Positions', 'callback', 'asktick');

	QTEMP1 = uimenu(T1Fig, 'label', 'Macro', 'Position', [4]);
		uimenu(QTEMP1, 'label', 'Start Recording Macro', 'callback', 'QmatNMR.buttonList=1; QmatNMR.uiInput1=2; regelstartrecordingmacro', 'separator', 'on');
		uimenu(QTEMP1, 'label', 'Stop Recording Macro', 'callback', 'askstoprecordingmacro');
		uimenu(QTEMP1, 'label', 'Execute Macro', 'callback', 'QmatNMR.StepWise = 0; askexecutemacro', 'accelerator', 'e');
		uimenu(QTEMP1, 'label', 'Execute Macro Stepwise', 'callback', 'QmatNMR.StepWise = 1; askexecutemacro');

	QmatNMR.Q5 = uimenu('parent', T1Fig, 'label', '   Create Output   ', 'Position', [5]);
		uimenu(QmatNMR.Q5, 'label', 'Printing Menu', 'callback', 'figure(findobj(allchild(0),''tag'',''T1fit'')); matprint;', 'accelerator', 'p');
		uimenu(QmatNMR.Q5, 'label', 'Save plot on disk', 'callback', 'asksavefitdisk');
  		uimenu(QmatNMR.Q5, 'label', 'Copy Figure', 'callback', 'figure(findobj(allchild(0),''tag'',''T1fit'')); copyfignmr');

        QTEMP1 = uimenu('parent', T1Fig, 'label', '   HELP ?   ', 'position', [6]);
	  uimenu(QTEMP1, 'label', 'Copyright', 'callback', 'matnmrhelp(''Copyright.hlp'', ''Copyright'')');
 	  uimenu(QTEMP1, 'label', 'Help desk', 'callback', ['web file://' QmatNMR.HelpPath filesep 'manual' filesep 'index.html;']);

	QmatNMR.Q6 = uimenu('parent', T1Fig, 'label', '   Clear Functions   ', 'position', [7]);
		uimenu(QmatNMR.Q6, 'label', 'Clear Functions', 'callback', 'clear functions; disp(''Clear Functions performed ...''); Arrowhead');

	%
	%set the foreground colour of the uimenu according to the colour scheme
	%
	set(findobj(T1Fig, 'type', 'uimenu'), 'foregroundcolor', QmatNMR.ColorScheme.UImenuFore);



	%  Uicontrol Object Creation 
		
	stopbut = uicontrol('parent', T1Fig, 'Style', 'Pushbutton', ...
		'Units', 'Normalized', ...
		'Position', [0.0 0.0 .11 .08], ...
		'String', 'Close', ...
		'BackGroundColor', QmatNMR.ColorScheme.Button3Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button3Fore, ...
		'callback', 'askstopT1fit');
		
	printbut = uicontrol('parent', T1Fig, 'Style', 'PushButton', ...
		'Units', 'Normalized', ...
		'Position', [0.115 0.0 .11 .08], ...
		'String', 'Print', ...
		'BackGroundColor', QmatNMR.ColorScheme.Button6Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button6Fore, ...
		'Callback', 'T1print');	

	ed(11) = uicontrol('parent', T1Fig, ... 					%sigma (normalization of Chi^2)
		'Units','normalized',... 
		'Position',[ 0.23 0.09 0.15 0.04 ],... 
		'Style','edit',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','ed(11)');
		
	TolBut  = uicontrol('parent', T1Fig, 'Style', 'Edit', ...
		'Units', 'Normalized', ...
		'Position', [0.23 .13 .15 .04], ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'String', '1e-5');
		
	NrIterBut = uicontrol('parent', T1Fig, 'Style', 'Edit', ...
		'Units', 'Normalized', ...
		'Position', [0.23 .17 .15 .04], ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'String', '100');
	        	
	logbut = uicontrol('parent', T1Fig, ... 
		'CallBack','T1fit(''logbut'');',... 
		'Units','normalized',... 
		'Position',[ 0 0.255 0.15 0.03 ],... 
		'String','Log plot y-axis',... 
		'Style','Check',... 
                'Value', 0, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'Visible','on',... 
		'UserData','logbut');
	        	
	logbut2 = uicontrol('parent', T1Fig, ... 
		'CallBack','if (get(gco, ''value'')==1); set(gca, ''xscale'', ''log''); else; set(gca, ''xscale'', ''linear''); end',... 
		'Units','normalized',... 
		'Position',[ 0.2 0.255 0.15 0.03 ],... 
		'String','Log plot x-axis',... 
		'Style','Check',... 
                'Value', 1, ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'Visible','on',... 
		'UserData','logbut2');
	        	
	fitbut = uicontrol('parent', T1Fig, ... 
		'CallBack','T1fit(''fitbut'');',... 
		'Units','normalized',... 
		'Position',[ 0 0.16 0.11 0.08 ],... 
		'String','Fit',... 
		'Style','pushbutton',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button4Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button4Fore, ...
		'Visible','on',... 
		'UserData','fitbut');
	
	refreshbut = uicontrol('parent', T1Fig, ... 
		'CallBack','T1fit(''refreshbut'');',... 
		'Units','normalized',... 
		'Position',[ 0 0.08 0.11 0.08 ],... 
		'String','Refresh',... 
		'Style','pushbutton',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button5Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button5Fore, ...
		'Visible','on',... 
		'UserData','refreshbut');
	
	lijstbut = uicontrol('parent', T1Fig, ... 
		'CallBack','T1fit(''lijstbut'');',... 
		'Units','normalized',... 
		'Position',[ 0.23 0.04 0.15 0.04 ],... 
		'String','Ext. Output',... 
		'Style','checkbox',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','lijstbut');  

	simplexbut = uicontrol('parent', T1Fig, ... 
		'CallBack','T1fit(''simplexbut'');',... 
		'Units','normalized',... 
		'Position',[ 0.23 0.00 0.15 0.04 ],... 
		'String','Simplex prefit',... 
		'Style','checkbox',... 
		'Visible','on',... 
		'UserData','simplexbut', ...
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'Value', 1);  

	redisbut = uicontrol('parent', T1Fig, ... 
		'CallBack','T1fit(''redisbut'');',... 
		'Units','normalized',... 
		'Position',[ 0.23 0.21 0.15 0.04 ],... 
		'String',' Off | 1 | 5 | 10 | 25 | 50 | 100 ',... 
		'Style','Popup',... 
		'Visible','on',...
                'Value', 2,... 
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','redisbut');  
		
		
		
%to whoever wants to edit this. The original was a complete mess, because it didn't say whatsoever
%which buttons belonged to what variable. 
%Now I hope it has improved somewhat. 
%All buttons on the that are meant for parameter input are arranged according to the height on the screen (lines)
%They consist of two edit buttons and two check buttons
%All button handles are put into the figure userdata such that the routine can always access them !

	ed(10) = uicontrol('parent', T1Fig, ... 				%Amplitude
		'Units','normalized',... 
		'Position',[ 0.465 0.16 0.11 0.05 ],... 
		'Style','edit',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','ed(10)'); 
	ck(10) = uicontrol('parent', T1Fig, ... 
		'Units','normalized',... 
		'Position',[ 0.435 0.16 0.03 0.05 ],... 
		'Style','checkbox',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','ck(10)'); 


	ed(9) = uicontrol('parent', T1Fig, ... 					%Constant
		'Units','normalized',... 
		'Position',[ 0.465 0.01 0.11 0.05 ],... 
		'Style','edit',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','ed(9)'); 
	ck(9) = uicontrol('parent', T1Fig, ... 
		'Units','normalized',... 
		'Position',[ 0.435 0.01 0.03 0.05 ],... 
		'Style','checkbox',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','ck(9)'); 



	ck(8) = uicontrol('parent', T1Fig, ... 					%Fourth line of parameters (bottom of screen)
		'Units','normalized',... 
		'Position',[ 0.88 0.01 0.03 0.05 ],... 
		'Style','checkbox',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','ck(8)'); 
	ed(8) = uicontrol('parent', T1Fig, ... 
		'Units','normalized',... 
		'Position',[ 0.77 0.01 0.11 0.05 ],... 
		'Style','edit',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','ed(8)'); 
	ed(7) = uicontrol('parent', T1Fig, ... 
		'Units','normalized',... 
		'Position',[ 0.63 0.01 0.11 0.05 ],... 
		'Style','edit',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','ed(7)'); 
	ck(7) = uicontrol('parent', T1Fig, ... 
		'Units','normalized',... 
		'Position',[ 0.601 0.01 0.03 0.05 ],... 
		'Style','checkbox',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','ck(7)'); 


	ck(6) = uicontrol('parent', T1Fig, ... 					%Third line of parameters
		'Units','normalized',... 
		'Position',[ 0.88 0.06 0.03 0.05 ],... 
		'Style','checkbox',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','ck(6)'); 
	ed(6) = uicontrol('parent', T1Fig, ... 
		'Units','normalized',... 
		'Position',[ 0.77 0.06 0.11 0.05 ],... 
		'Style','edit',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','ed(6)'); 
	ed(5) = uicontrol('parent', T1Fig, ... 
		'Units','normalized',... 
		'Position',[ 0.63 0.06 0.11 0.05 ],... 
		'Style','edit',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','ed(5)'); 
	ck(5) = uicontrol('parent', T1Fig, ... 
		'Units','normalized',... 
		'Position',[ 0.601 0.06 0.03 0.05 ],... 
		'Style','checkbox',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','ck(5)'); 


	ck(4) = uicontrol('parent', T1Fig, ... 					%Second line of parameters
		'Units','normalized',... 
		'Position',[ 0.88 0.11 0.03 0.05 ],... 
		'Style','checkbox',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','ck(4)'); 
	ed(4) = uicontrol('parent', T1Fig, ... 
		'Units','normalized',... 
		'Position',[ 0.77 0.11 0.11 0.05 ],... 
		'Style','edit',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','ed(4)'); 
	ed(3) = uicontrol('parent', T1Fig, ... 
		'Units','normalized',... 
		'Position',[ 0.63 0.11 0.11 0.05 ],... 
		'Style','edit',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','ed(3)'); 
	ck(3) = uicontrol('parent', T1Fig, ... 
		'Units','normalized',... 
		'Position',[ 0.601 0.11 0.03 0.05 ],... 
		'Style','checkbox',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','ck(3)'); 


	ck(2) = uicontrol('parent', T1Fig, ... 					%First line of parameters
		'Units','normalized',... 
		'Position',[ 0.88 0.16 0.03 0.05 ],... 
		'Style','checkbox',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','ck(2)'); 
	ed(2) = uicontrol('parent', T1Fig, ... 
		'Units','normalized',... 
		'Position',[ 0.77 0.16 0.11 0.05 ],... 
		'Style','edit',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','ed(2)');
	ed(1) = uicontrol('parent', T1Fig, ... 
		'Units','normalized',... 
		'Position',[ 0.63 0.16 0.11 0.05 ],... 
		'Style','edit',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','ed(1)'); 
	ck(1) = uicontrol('parent', T1Fig, ... 
		'Units','normalized',... 
		'Position',[ 0.601 0.16 0.03 0.05 ],... 
		'Style','checkbox',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button1Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button1Fore, ...
		'UserData','ck(1)'); 

	handle_ui_list = [ fitbut ed(1) ed(2) ed(3) ed(4) ed(5) ed(6) ed(7) ed(8) ed(9) ed(10) ed(11) ...
			   ck(1) ck(2) ck(3) ck(4) ck(5) ck(6) ck(7) ck(8) ck(9) ck(10) ...
			   TolBut NrIterBut redisbut lijstbut simplexbut stopbut printbut refreshbut logbut]; 


	%  Text Object Creation 
	txt1 = uicontrol('parent', T1Fig, ... 				%Coefficient
		'Units','normalized',... 
		'Position',[ 0.601 0.21 0.14 0.04 ],... 
		'Style','pushbutton',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button7Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button7Fore, ...
		'String','Coefficient'); 
	txt2 = uicontrol('parent', T1Fig, ... 				%T1
		'Units','normalized',... 
		'Position',[ 0.77 0.21 0.14 0.04 ],... 
		'Style','pushbutton',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button7Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button7Fore, ...
		'String','T'); 
	txt5 = uicontrol('parent', T1Fig, ... 				%Constant
		'Units','normalized',... 
		'Position',[ 0.435 0.06 0.14 0.04 ],... 
		'Style','pushbutton',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button7Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button7Fore, ...
		'String','Constant'); 
	txt6 = uicontrol('parent', T1Fig, ... 				%Amplitude
		'Units','normalized',... 
		'Position',[ 0.435 0.21 0.14 0.04 ],... 
		'Style','pushbutton',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button7Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button7Fore, ...
		'String','Amplitude'); 
	txt7 = uicontrol('parent', T1Fig, ... 				%Tolerance
		'Units','normalized',... 
		'Position',[ 0.12 0.13 0.11 0.04 ],... 
		'Style','pushbutton',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button7Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button7Fore, ...
		'String','Tolerance'); 
	txt8 = uicontrol('parent', T1Fig, ... 				%Max. Nr Iter.
		'Units','normalized',... 
		'Position',[ 0.12 0.17 0.11 0.04 ],... 
		'Style','pushbutton',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button7Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button7Fore, ...
		'String','Max. Nr Iter.'); 
	txt9 = uicontrol('parent', T1Fig, ... 				%Redisplay no.
		'Units','normalized',... 
		'Position',[ 0.12 0.21 0.11 0.04 ],... 
		'Style','pushbutton',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button7Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button7Fore, ...
		'String','Redisplay no.');
	txt11 = uicontrol('parent', T1Fig, ... 					%sigma (normalization of Chi^2)
		'Units','normalized',... 
		'Position',[ 0.12 0.09 0.11 0.04 ],... 
		'Style','pushbutton',... 
		'Units','normalized',... 
		'Visible','on',... 
		'BackGroundColor', QmatNMR.ColorScheme.Button7Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button7Fore, ...
		'String','Sigma');
		
	txt10 = uicontrol('parent', T1Fig, ... 					%functional
		'Units','normalized',... 
		'Position',[ 0.10 0.945 0.80 0.05 ],... 
		'Style','pushbutton',... 
		'Units','normalized',... 
		'Visible','on',... 
                'Callback', 'delete(gco)', ...
		'BackGroundColor', QmatNMR.ColorScheme.Button7Back, ...
		'ForeGroundColor', QmatNMR.ColorScheme.Button7Fore, ...
		'String','Fit:    Amplitude*(Constant + Coefficient*exp(-time/T) + ...)');

	handle_txt_list = [txt1 txt2 txt5 txt6 txt7 txt8 txt9 txt10 txt11];
	handle_list = [handle_ui_list handle_txt_list logbut2]; 
	QTEMP.Handles = handle_list;
	set(handle_list, 'fontsize', QmatNMR.UIFontSize);
	set(txt10, 'fontsize', QmatNMR.UIFontSize+4);
	set(T1Fig, 'userdata',QTEMP, 'units', 'normalized', ...
                'position', [QmatNMR.Q2D3DViewerLeft QmatNMR.Q2D3DViewerBottom QmatNMR.Q2D3DViewerWidth QmatNMR.Q2D3DViewerHeight], 'Visible', 'on');

        delete(findobj(allchild(gcf), 'type', 'axes'));
	T1FitAxis=axes('units', 'normalized', ...
	                 'position',[0.05 0.32 .9 .62], ...
			 'nextplot', 'replacechildren', ...
                         'XGrid','on', ...
			 'YGrid','on', ...
			 'FontSize', QmatNMR.TextSize, ...
			 'FontName', QmatNMR.TextFont, ...
			 'FontAngle', QmatNMR.TextAngle, ...
			 'FontWeight', QmatNMR.TextWeight, ...
			 'LineWidth', QmatNMR.LineWidth, ...
			 'visible','on', ...
			 'tag', 'T1FitAxis', ...
			 'view', [0 90], ...
			 'color', QmatNMR.ColorScheme.AxisBack, ...
			 'xcolor', QmatNMR.ColorScheme.AxisFore, ...
			 'ycolor', QmatNMR.ColorScheme.AxisFore, ...
			 'zcolor', QmatNMR.ColorScheme.AxisFore, ...
			 'visible', 'on', ...
			 'xscale', 'linear', ...
			 'yscale', 'log', ...
			 'zscale', 'linear', ...
			 'xtickmode', 'auto', ...
			 'ytickmode', 'auto', ...
			 'ztickmode', 'auto', ...
			 'xticklabelmode', 'auto', ...
			 'yticklabelmode', 'auto', ...
			 'zticklabelmode', 'auto', ...
			 'selected', 'off', ...
                         'xdir', 'normal', ...
			 'userdata', 1, ...
			 'box', 'on');

	%
	%set the colours of the colour scheme also for the title
	%
	set(get(T1FitAxis, 'title'), 'color', QmatNMR.ColorScheme.AxisFore);
